"""
Compare vision navcalcs pose estimates against TSPI / NovAtel DGPS truth.

This script takes three files:

  1. A probe/receiver navcalcs CSV generated by the pose pipeline.
  2. A tanker/target navcalcs CSV generated by the pose pipeline.
  3. A whitespace-delimited NovAtel / TSPI text file containing the relative
     base-to-rover ECEF vector.

For each pose method, the script:

  * synchronizes probe, tanker, and TSPI rows using image_time / GPS time-of-week;
  * applies lever-arm corrections from object origins to NovAtel antenna locations;
  * subtracts receiver antenna from tanker antenna to form a vision-estimated
    antenna-to-antenna vector;
  * compares that vector with the TSPI base-to-rover vector, with automatic sign
    selection available;
  * generates x/y/z/range tracking plots, x/y/z/range error plots, vector-error
    norm plots, and summary CSV/Markdown tables.

Default lever arms are the values supplied during dissertation analysis:

    receiver probe-tip to receiver antenna, receiver frame:
        [-9.27027, 0.45487, 0.67881]

    tanker geometric center to tanker antenna, tanker frame:
        [7.78935, -0.00469, -0.06247]

Important coordinate note:
    By default, the script compares the TSPI vector directly to the vision vector
    after the optional sign flip. If the TSPI ECEF axes must be rotated into the
    receiver-camera/processing frame, provide --truth-transform with nine row-major
    matrix entries.

Example:
    python truth_compare_navcalcs.py \
        --probe-csv navcalcs_PROBE_BothContext_01062024_0_3M.csv \
        --tanker-csv navcalcs_GIII_Pseudo.csv \
        --novatel-txt relative_tspi.txt \
        --out truth_compare_probe_tanker

Optional fixed sign convention:
    python truth_compare_navcalcs.py ... --truth-sign -1

Optional truth-frame transform, row-major 3x3:
    python truth_compare_navcalcs.py ... --truth-transform 1 0 0 0 1 0 0 0 1
"""

from __future__ import annotations

import argparse
import math
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# -----------------------------------------------------------------------------
# Method definitions
# -----------------------------------------------------------------------------

@dataclass(frozen=True)
class MethodSpec:
    key: str
    label: str
    valid_col: str
    q_cols: tuple[str, str, str, str]
    t_cols: tuple[str, str, str]


METHODS: tuple[MethodSpec, ...] = (
    MethodSpec(
        key="pnp",
        label="OpenCV SolvePnP",
        valid_col="pnp_valid",
        q_cols=("pnp_qw", "pnp_qx", "pnp_qy", "pnp_qz"),
        t_cols=("pnp_tvec_x", "pnp_tvec_y", "pnp_tvec_z"),
    ),
    MethodSpec(
        key="qnp",
        label="SolveQnP",
        valid_col="qnp_valid",
        q_cols=("qnp_qw", "qnp_qx", "qnp_qy", "qnp_qz"),
        t_cols=("qnp_tvec_x", "qnp_tvec_y", "qnp_tvec_z"),
    ),
    MethodSpec(
        key="wqnp_yolo",
        label="wQnP, YOLO centers + KF covariance",
        valid_col="wqnp_yolo_valid",
        q_cols=("wqnp_yolo_qw", "wqnp_yolo_qx", "wqnp_yolo_qy", "wqnp_yolo_qz"),
        t_cols=("wqnp_yolo_tvec_x", "wqnp_yolo_tvec_y", "wqnp_yolo_tvec_z"),
    ),
    MethodSpec(
        key="wqnp_kfest",
        label="wQnP, KF centers + KF covariance",
        valid_col="wqnp_kfest_valid",
        q_cols=("wqnp_kfest_qw", "wqnp_kfest_qx", "wqnp_kfest_qy", "wqnp_kfest_qz"),
        t_cols=("wqnp_kfest_tvec_x", "wqnp_kfest_tvec_y", "wqnp_kfest_tvec_z"),
    ),
)


DEFAULT_RECEIVER_PROBE_TO_ANTENNA = np.array([-8.42027, 0.45487, 0.67881], dtype=float)
DEFAULT_TANKER_CENTER_TO_ANTENNA = np.array([7.78935, -0.00469, -0.06247], dtype=float)
GPS_WEEK_SECONDS = 604800.0
UNIX_TO_GPS_EPOCH_SECONDS = (datetime(1980, 1, 6, tzinfo=timezone.utc) - datetime(1970, 1, 1, tzinfo=timezone.utc)).total_seconds()
GPS_MINUS_UTC_LEAP_SECONDS = 18.0


# -----------------------------------------------------------------------------
# Basic helpers
# -----------------------------------------------------------------------------

def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def have_cols(df: pd.DataFrame, cols: Iterable[str]) -> bool:
    return all(c in df.columns for c in cols)


def as_bool(series: pd.Series) -> np.ndarray:
    if series.dtype == bool:
        return series.fillna(False).to_numpy(dtype=bool)
    if pd.api.types.is_numeric_dtype(series):
        return (series.fillna(0).astype(float) != 0.0).to_numpy(dtype=bool)
    true_values = {"true", "t", "1", "yes", "y", "valid"}
    return series.fillna("false").astype(str).str.strip().str.lower().isin(true_values).to_numpy(dtype=bool)


def numeric(df: pd.DataFrame, cols: Iterable[str]) -> np.ndarray:
    return df.loc[:, list(cols)].apply(pd.to_numeric, errors="coerce").to_numpy(dtype=float)


def finite_rows(arr: np.ndarray) -> np.ndarray:
    return np.all(np.isfinite(arr), axis=1)


def vector_norm(arr: np.ndarray) -> np.ndarray:
    return np.linalg.norm(arr, axis=1)


def finite_stats(values: np.ndarray | pd.Series) -> dict[str, float | int]:
    arr = np.asarray(values, dtype=float)
    arr = arr[np.isfinite(arr)]
    if arr.size == 0:
        return {
            "count": 0,
            "mean": np.nan,
            "median": np.nan,
            "rmse": np.nan,
            "mae": np.nan,
            "p05": np.nan,
            "p95": np.nan,
            "max_abs": np.nan,
        }
    return {
        "count": int(arr.size),
        "mean": float(np.mean(arr)),
        "median": float(np.median(arr)),
        "rmse": float(np.sqrt(np.mean(arr ** 2))),
        "mae": float(np.mean(np.abs(arr))),
        "p05": float(np.percentile(arr, 5)),
        "p95": float(np.percentile(arr, 95)),
        "max_abs": float(np.max(np.abs(arr))),
    }


def write_markdown_table(df: pd.DataFrame, path: Path, float_fmt: str = ".5g") -> None:
    def fmt(x: object) -> str:
        if isinstance(x, (float, np.floating)):
            if math.isnan(float(x)):
                return ""
            return format(float(x), float_fmt)
        return str(x)

    cols = list(df.columns)
    lines = ["| " + " | ".join(cols) + " |", "| " + " | ".join(["---"] * len(cols)) + " |"]
    for _, row in df.iterrows():
        lines.append("| " + " | ".join(fmt(row[c]) for c in cols) + " |")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def get_plot_time_axis(df: pd.DataFrame) -> tuple[np.ndarray, str]:
    """Return the best available x-axis series and label for plots."""
    for col, label in [
        ("image_time", "Image time (s)"),
        ("image_time_probe", "Probe image time (s)"),
        ("sync_time_s", "GPS-aligned sync time (s)"),
    ]:
        if col in df.columns:
            return df[col].to_numpy(dtype=float), label
    raise KeyError("No usable plot time column found. Expected one of: image_time, image_time_probe, sync_time_s.")


def unix_to_gps_seconds(unix_seconds: np.ndarray) -> np.ndarray:
    """Convert Unix UTC seconds to GPS seconds on the continuous GPS timescale."""
    return np.asarray(unix_seconds, dtype=float) - UNIX_TO_GPS_EPOCH_SECONDS + GPS_MINUS_UTC_LEAP_SECONDS


def prepare_navcalcs_sync_time(df: pd.DataFrame) -> pd.DataFrame:
    """Add sync columns derived from image_time.

    Navcalcs files typically store image_time as Unix epoch seconds. TSPI files
    provide GPS week and time-of-week, so synchronization must happen on a
    common timescale.
    """
    out = df.copy()
    image_time = out["image_time"].to_numpy(dtype=float)

    # Large values are treated as Unix epoch seconds; smaller values are assumed
    # to already be in a GPS-relative scale compatible with the TSPI file.
    if np.nanmedian(image_time) > 1.0e9:
        sync_time = unix_to_gps_seconds(image_time)
    else:
        sync_time = image_time

    out["sync_time_s"] = sync_time
    out["sync_gps_week"] = np.floor(sync_time / GPS_WEEK_SECONDS)
    out["sync_gps_tow"] = sync_time - out["sync_gps_week"] * GPS_WEEK_SECONDS
    return out


# -----------------------------------------------------------------------------
# Quaternion / rotation helpers
# -----------------------------------------------------------------------------

def quat_to_rotmat_batch(q: np.ndarray) -> np.ndarray:
    """Return R(q) for scalar-first quaternions, row-wise.

    The returned rotation maps object-frame vectors into the camera/estimator frame
    under the convention used by the navcalcs pose output.
    """
    q = q.astype(float)
    n = np.linalg.norm(q, axis=1, keepdims=True)
    n[n == 0.0] = np.nan
    q = q / n

    w, x, y, z = q[:, 0], q[:, 1], q[:, 2], q[:, 3]
    R = np.empty((len(q), 3, 3), dtype=float)

    R[:, 0, 0] = 1.0 - 2.0 * (y * y + z * z)
    R[:, 0, 1] = 2.0 * (x * y - z * w)
    R[:, 0, 2] = 2.0 * (x * z + y * w)

    R[:, 1, 0] = 2.0 * (x * y + z * w)
    R[:, 1, 1] = 1.0 - 2.0 * (x * x + z * z)
    R[:, 1, 2] = 2.0 * (y * z - x * w)

    R[:, 2, 0] = 2.0 * (x * z - y * w)
    R[:, 2, 1] = 2.0 * (y * z + x * w)
    R[:, 2, 2] = 1.0 - 2.0 * (x * x + y * y)
    return R


def rotate_vectors_batch(R: np.ndarray, v: np.ndarray) -> np.ndarray:
    """Compute R_i @ v for all rows."""
    return np.einsum("nij,j->ni", R, v)


# -----------------------------------------------------------------------------
# Loading and synchronization
# -----------------------------------------------------------------------------

def load_navcalcs(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    if "image_time" not in df.columns:
        raise ValueError(f"{path} does not contain an image_time column.")
    df = df.copy()
    df["image_time"] = pd.to_numeric(df["image_time"], errors="coerce")
    df = df[np.isfinite(df["image_time"])].sort_values("image_time").reset_index(drop=True)
    return prepare_navcalcs_sync_time(df)


def load_novatel_tspi(path: Path) -> pd.DataFrame:
    """Load whitespace-delimited 28-column TSPI/DGPS data.

    Column mapping follows the user-provided header table:
        1  GPS time of week
        5  Vector Base to Rover ECEF-X Location
        7  Vector Base to Rover ECEF-Y Location
        9  Vector Base to Rover ECEF-Z Location
        28 GPS week
    """
    df = pd.read_csv(path, sep=r"\s+", header=None, comment="#", engine="python")
    if df.shape[1] < 28:
        raise ValueError(f"Expected at least 28 TSPI columns; found {df.shape[1]} in {path}")

    names = [
        "gps_tow",
        "rover_ecef_x", "rover_ecef_y", "rover_ecef_z",
        "base_to_rover_ecef_x", "base_to_rover_ecef_x_std",
        "base_to_rover_ecef_y", "base_to_rover_ecef_y_std",
        "base_to_rover_ecef_z", "base_to_rover_ecef_z_std",
        "ecef_vx", "ecef_vx_std",
        "ecef_vy", "ecef_vy_std",
        "ecef_vz", "ecef_vz_std",
        "gps_satellites", "quality_number", "ddop", "ca_rms", "l1_rms", "double_difference_dop",
        "fwd_rev_sep_east", "fwd_rev_sep_north", "fwd_rev_sep_height",
        "forward_combined_weighting", "reverse_combined_weighting", "gps_week",
    ]
    out = df.iloc[:, :28].copy()
    out.columns = names
    for c in out.columns:
        out[c] = pd.to_numeric(out[c], errors="coerce")
    out["truth_sync_time_s"] = out["gps_week"] * GPS_WEEK_SECONDS + out["gps_tow"]
    out = out[np.isfinite(out["truth_sync_time_s"])].sort_values("truth_sync_time_s").reset_index(drop=True)
    return out


def merge_probe_tanker_truth(
    probe: pd.DataFrame,
    tanker: pd.DataFrame,
    tspi: pd.DataFrame,
    sync_tolerance: float,
) -> pd.DataFrame:
    probe = probe.sort_values("sync_time_s").reset_index(drop=True)
    tanker = tanker.sort_values("sync_time_s").reset_index(drop=True)
    tspi = tspi.sort_values("truth_sync_time_s").reset_index(drop=True)

    merged = pd.merge_asof(
        probe,
        tanker,
        on="sync_time_s",
        direction="nearest",
        tolerance=sync_tolerance,
        suffixes=("_probe", "_tanker"),
    )

    # Track tanker synchronization residual if the original column survived via suffixes.
    # With merge_asof(on='sync_time_s'), both rows share the selected key. This is fine for
    # first-pass analysis because both navcalcs files are normally generated from the same
    # image clock.
    merged = pd.merge_asof(
        merged.sort_values("sync_time_s"),
        tspi,
        left_on="sync_time_s",
        right_on="truth_sync_time_s",
        direction="nearest",
        tolerance=sync_tolerance,
    )
    merged["truth_time_error_s"] = merged["sync_time_s"] - merged["truth_sync_time_s"]
    return merged.reset_index(drop=True)


# -----------------------------------------------------------------------------
# Vision vector reconstruction and truth comparison
# -----------------------------------------------------------------------------

def method_columns_with_suffix(m: MethodSpec, suffix: str) -> tuple[str, tuple[str, ...], tuple[str, ...]]:
    return (
        f"{m.valid_col}_{suffix}",
        tuple(f"{c}_{suffix}" for c in m.q_cols),
        tuple(f"{c}_{suffix}" for c in m.t_cols),
    )


def method_available_in_merged(df: pd.DataFrame, m: MethodSpec) -> bool:
    p_valid, p_q, p_t = method_columns_with_suffix(m, "probe")
    t_valid, t_q, t_t = method_columns_with_suffix(m, "tanker")
    return have_cols(df, [p_valid, *p_q, *p_t, t_valid, *t_q, *t_t])


def compute_vision_vectors(
    df: pd.DataFrame,
    methods: list[MethodSpec],
    receiver_probe_to_antenna: np.ndarray,
    tanker_center_to_antenna: np.ndarray,
) -> pd.DataFrame:
    out = df.copy()

    for m in methods:
        p_valid_col, p_q_cols, p_t_cols = method_columns_with_suffix(m, "probe")
        t_valid_col, t_q_cols, t_t_cols = method_columns_with_suffix(m, "tanker")

        valid = as_bool(out[p_valid_col]) & as_bool(out[t_valid_col])

        q_probe = numeric(out, p_q_cols)
        t_probe = numeric(out, p_t_cols)
        q_tanker = numeric(out, t_q_cols)
        t_tanker = numeric(out, t_t_cols)

        R_probe = quat_to_rotmat_batch(q_probe)
        R_tanker = quat_to_rotmat_batch(q_tanker)

        p_receiver_ant = t_probe + rotate_vectors_batch(R_probe, receiver_probe_to_antenna)
        p_tanker_ant = t_tanker + rotate_vectors_batch(R_tanker, tanker_center_to_antenna)
        vision_vec = p_tanker_ant - p_receiver_ant

        finite = finite_rows(p_receiver_ant) & finite_rows(p_tanker_ant) & finite_rows(vision_vec)
        valid &= finite

        for i, axis in enumerate("xyz"):
            out[f"{m.key}_receiver_ant_{axis}"] = p_receiver_ant[:, i]
            out[f"{m.key}_tanker_ant_{axis}"] = p_tanker_ant[:, i]
            out[f"{m.key}_vision_vec_{axis}"] = vision_vec[:, i]
        out[f"{m.key}_vision_range"] = vector_norm(vision_vec)
        out[f"{m.key}_truth_compare_valid"] = valid

    return out


def add_truth_vectors(
    df: pd.DataFrame,
    truth_transform: np.ndarray | None,
) -> pd.DataFrame:
    out = df.copy()
    truth = numeric(out, ["base_to_rover_ecef_x", "base_to_rover_ecef_y", "base_to_rover_ecef_z"])

    if truth_transform is not None:
        truth = truth @ truth_transform.T

    for i, axis in enumerate("xyz"):
        out[f"truth_raw_{axis}"] = numeric(out, ["base_to_rover_ecef_x", "base_to_rover_ecef_y", "base_to_rover_ecef_z"])[:, i]
        out[f"truth_cmp_base_to_rover_{axis}"] = truth[:, i]
    out["truth_cmp_base_to_rover_range"] = vector_norm(truth)
    return out


def choose_truth_sign(df: pd.DataFrame, methods: list[MethodSpec], truth_sign: str) -> tuple[int, pd.DataFrame]:
    rows = []
    truth = numeric(df, ["truth_cmp_base_to_rover_x", "truth_cmp_base_to_rover_y", "truth_cmp_base_to_rover_z"])

    for sign in (+1, -1):
        all_errs = []
        for m in methods:
            valid_col = f"{m.key}_truth_compare_valid"
            if valid_col not in df.columns:
                continue
            vision = numeric(df, [f"{m.key}_vision_vec_x", f"{m.key}_vision_vec_y", f"{m.key}_vision_vec_z"])
            valid = df[valid_col].fillna(False).to_numpy(dtype=bool) & finite_rows(vision) & finite_rows(truth)
            if np.any(valid):
                err_norm = vector_norm(vision[valid] - sign * truth[valid])
                all_errs.append(err_norm)
        if all_errs:
            arr = np.concatenate(all_errs)
            stats = finite_stats(arr)
        else:
            stats = finite_stats(np.array([], dtype=float))
        rows.append({"truth_sign": sign, **stats})

    diag = pd.DataFrame(rows)
    if truth_sign.lower() == "auto":
        usable = diag[np.isfinite(diag["median"])]
        if usable.empty:
            chosen = 1
        else:
            chosen = int(usable.sort_values("median").iloc[0]["truth_sign"])
    else:
        chosen = int(truth_sign)
        if chosen not in (-1, 1):
            raise ValueError("--truth-sign must be 'auto', '1', or '-1'.")

    return chosen, diag


def add_errors(df: pd.DataFrame, methods: list[MethodSpec], sign: int) -> pd.DataFrame:
    out = df.copy()
    truth = sign * numeric(out, ["truth_cmp_base_to_rover_x", "truth_cmp_base_to_rover_y", "truth_cmp_base_to_rover_z"])
    for i, axis in enumerate("xyz"):
        out[f"truth_{axis}"] = truth[:, i]
    out["truth_range"] = vector_norm(truth)

    for m in methods:
        vision = numeric(out, [f"{m.key}_vision_vec_x", f"{m.key}_vision_vec_y", f"{m.key}_vision_vec_z"])
        err = vision - truth
        valid = out[f"{m.key}_truth_compare_valid"].fillna(False).to_numpy(dtype=bool) & finite_rows(vision) & finite_rows(truth)

        for i, axis in enumerate("xyz"):
            out[f"{m.key}_err_{axis}"] = np.where(valid, err[:, i], np.nan)
        out[f"{m.key}_err_norm"] = np.where(valid, vector_norm(err), np.nan)
        out[f"{m.key}_range_error"] = np.where(valid, out[f"{m.key}_vision_range"].to_numpy(dtype=float) - out["truth_range"].to_numpy(dtype=float), np.nan)
    return out


def summarize_truth_errors(df: pd.DataFrame, methods: list[MethodSpec]) -> pd.DataFrame:
    rows = []
    for m in methods:
        valid = df.get(f"{m.key}_truth_compare_valid", pd.Series(False, index=df.index)).fillna(False).to_numpy(dtype=bool)
        row = {"method": m.label, "key": m.key, "valid_samples": int(np.sum(valid)), "total_samples": int(len(df))}
        for quantity, col in [
            ("x", f"{m.key}_err_x"),
            ("y", f"{m.key}_err_y"),
            ("z", f"{m.key}_err_z"),
            ("range", f"{m.key}_range_error"),
            ("vector_norm", f"{m.key}_err_norm"),
        ]:
            stats = finite_stats(df[col] if col in df.columns else np.array([]))
            for stat_name in ["mean", "median", "rmse", "mae", "p05", "p95", "max_abs"]:
                row[f"{quantity}_{stat_name}"] = stats[stat_name]
            row[f"{quantity}_count"] = stats["count"]
        rows.append(row)
    return pd.DataFrame(rows)


# -----------------------------------------------------------------------------
# Plotting
# -----------------------------------------------------------------------------

def savefig(path: Path) -> None:
    plt.tight_layout()
    plt.savefig(path, dpi=220)
    plt.close()


def plot_tracking(df: pd.DataFrame, methods: list[MethodSpec], out_dir: Path) -> None:
    x, xlabel = get_plot_time_axis(df)
    for axis in "xyz":
        plt.figure(figsize=(10, 5))
        plt.plot(x, df[f"truth_{axis}"], linewidth=2.0, label="TSPI/DGPS truth")
        for m in methods:
            col = f"{m.key}_vision_vec_{axis}"
            if col in df.columns:
                y = df[col].where(df[f"{m.key}_truth_compare_valid"], np.nan)
                plt.plot(x, y, linewidth=1.0, label=m.label)
        plt.xlabel(xlabel)
        plt.ylabel(f"{axis.upper()} component")
        plt.title(f"Antenna-to-antenna vector tracking: {axis.upper()}")
        plt.legend(fontsize="small")
        savefig(out_dir / f"tracking_{axis}.png")

    plt.figure(figsize=(10, 5))
    plt.plot(x, df["truth_range"], linewidth=2.0, label="TSPI/DGPS truth")
    for m in methods:
        col = f"{m.key}_vision_range"
        if col in df.columns:
            y = df[col].where(df[f"{m.key}_truth_compare_valid"], np.nan)
            plt.plot(x, y, linewidth=1.0, label=m.label)
    plt.xlabel(xlabel)
    plt.ylabel("Vector magnitude / range")
    plt.title("Antenna-to-antenna range tracking")
    plt.legend(fontsize="small")
    savefig(out_dir / "tracking_range.png")


def plot_errors(df: pd.DataFrame, methods: list[MethodSpec], out_dir: Path) -> None:
    x, xlabel = get_plot_time_axis(df)
    for quantity, ylabel, title, fname in [
        ("err_x", "X error", "Truth error: X component", "error_x.png"),
        ("err_y", "Y error", "Truth error: Y component", "error_y.png"),
        ("err_z", "Z error", "Truth error: Z component", "error_z.png"),
        ("range_error", "Range error", "Truth error: vector magnitude", "error_range.png"),
        ("err_norm", "3D error norm", "Truth error: 3D vector norm", "error_norm.png"),
    ]:
        plt.figure(figsize=(10, 5))
        for m in methods:
            col = f"{m.key}_{quantity}"
            if col in df.columns:
                plt.plot(x, df[col], linewidth=1.0, label=m.label)
        plt.xlabel(xlabel)
        plt.ylabel(ylabel)
        plt.title(title)
        plt.axhline(0.0, linewidth=0.8)
        plt.legend(fontsize="small")
        savefig(out_dir / fname)


def plot_summary_bars(summary: pd.DataFrame, out_dir: Path) -> None:
    if summary.empty:
        return
    for metric, ylabel, title, fname in [
        ("vector_norm_rmse", "RMSE of 3D vector error", "Truth-error RMSE", "summary_vector_norm_rmse.png"),
        ("vector_norm_median", "Median 3D vector error norm", "Median truth-error norm", "summary_vector_norm_median.png"),
        ("range_rmse", "Range-error RMSE", "Range truth-error RMSE", "summary_range_rmse.png"),
        ("range_median", "Median range error", "Median signed range error", "summary_range_median.png"),
        ("x_rmse", "X-error RMSE", "X truth-error RMSE", "summary_x_rmse.png"),
        ("y_rmse", "Y-error RMSE", "Y truth-error RMSE", "summary_y_rmse.png"),
        ("z_rmse", "Z-error RMSE", "Z truth-error RMSE", "summary_z_rmse.png"),
    ]:
        if metric not in summary.columns:
            continue
        plt.figure(figsize=(8, 4.5))
        plt.bar(summary["method"], summary[metric])
        plt.ylabel(ylabel)
        plt.title(title)
        plt.xticks(rotation=25, ha="right")
        savefig(out_dir / fname)


# -----------------------------------------------------------------------------
# Summary text
# -----------------------------------------------------------------------------

def build_summary_text(
    probe_csv: Path,
    tanker_csv: Path,
    novatel_txt: Path,
    df: pd.DataFrame,
    methods: list[MethodSpec],
    truth_sign: int,
    sign_diag: pd.DataFrame,
    err_summary: pd.DataFrame,
    sync_tolerance: float,
) -> str:
    lines: list[str] = []
    lines.append("TSPI/DGPS truth comparison")
    lines.append("==========================")
    lines.append("")
    lines.append(f"Probe CSV:   {probe_csv.name}")
    lines.append(f"Tanker CSV:  {tanker_csv.name}")
    lines.append(f"TSPI file:   {novatel_txt.name}")
    lines.append(f"Rows after synchronization attempt: {len(df)}")
    lines.append(f"Synchronization tolerance: {sync_tolerance:.6g} s")
    finite_truth = np.isfinite(df["gps_tow"].to_numpy(dtype=float)) if "gps_tow" in df.columns else np.zeros(len(df), dtype=bool)
    lines.append(f"Rows with matched TSPI truth: {int(np.sum(finite_truth))}")
    if "truth_time_error_s" in df.columns:
        dt = df["truth_time_error_s"].to_numpy(dtype=float)
        dt = dt[np.isfinite(dt)]
        if dt.size:
            lines.append(f"Truth sync residual: median={np.median(dt):.6g} s, max_abs={np.max(np.abs(dt)):.6g} s")
    lines.append("")

    lines.append("Truth sign diagnostic")
    lines.append("---------------------")
    lines.append(f"Chosen truth sign: {truth_sign}")
    for _, row in sign_diag.iterrows():
        lines.append(
            f"sign {int(row['truth_sign']):+d}: median vector error={row['median']:.6g}, "
            f"RMSE={row['rmse']:.6g}, count={int(row['count'])}"
        )
    lines.append("")

    lines.append("Method truth-error summary")
    lines.append("--------------------------")
    for _, row in err_summary.iterrows():
        lines.append(
            f"{row['method']}: samples={int(row['valid_samples'])}/{int(row['total_samples'])}, "
            f"vector RMSE={row['vector_norm_rmse']:.6g}, "
            f"median vector norm={row['vector_norm_median']:.6g}, "
            f"range RMSE={row['range_rmse']:.6g}, "
            f"x/y/z RMSE=({row['x_rmse']:.6g}, {row['y_rmse']:.6g}, {row['z_rmse']:.6g})"
        )
    lines.append("")

    best = err_summary[np.isfinite(err_summary["vector_norm_rmse"])].sort_values("vector_norm_rmse")
    if not best.empty:
        lines.append(f"Lowest 3D vector-error RMSE: {best.iloc[0]['method']}")
    lines.append("")
    lines.append("Coordinate note")
    lines.append("---------------")
    lines.append(
        "This first-pass comparison assumes the TSPI vector, after optional sign and optional "
        "--truth-transform, is expressed in the same component convention as the vision-derived "
        "antenna-to-antenna vector. If component errors show a clear axis permutation/sign pattern, "
        "rerun with --truth-transform."
    )
    return "\n".join(lines)


# -----------------------------------------------------------------------------
# CLI / main
# -----------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Compare probe/tanker navcalcs pose estimates against TSPI/DGPS truth.")
    parser.add_argument("--probe-csv", type=Path, help="Probe/receiver navcalcs CSV.")
    parser.add_argument("--tanker-csv", type=Path, help="Tanker/target navcalcs CSV.")
    parser.add_argument("--novatel-txt", type=Path, help="Whitespace-delimited NovAtel/TSPI relative-vector text file.")
    parser.add_argument("--out", type=Path, default=None, help="Output directory. Defaults to truth_compare_<probe>_<tanker>.")
    parser.add_argument("--sync-tolerance", type=float, default=0.075, help="Nearest-time synchronization tolerance in seconds. Default: 0.075.")
    parser.add_argument("--truth-sign", default="auto", choices=["auto", "1", "-1"], help="Sign applied to TSPI vector before comparison. Default: auto.")
    parser.add_argument(
        "--truth-transform",
        type=float,
        nargs=9,
        default=None,
        metavar=("r11", "r12", "r13", "r21", "r22", "r23", "r31", "r32", "r33"),
        help="Optional row-major 3x3 transform applied to TSPI vector before sign selection.",
    )
    parser.add_argument(
        "--receiver-probe-to-antenna",
        type=float,
        nargs=3,
        default=DEFAULT_RECEIVER_PROBE_TO_ANTENNA.tolist(),
        metavar=("X", "Y", "Z"),
        help="Receiver probe-tip to receiver antenna lever arm in receiver/probe frame.",
    )
    parser.add_argument(
        "--tanker-center-to-antenna",
        type=float,
        nargs=3,
        default=DEFAULT_TANKER_CENTER_TO_ANTENNA.tolist(),
        metavar=("X", "Y", "Z"),
        help="Tanker geometric center to tanker antenna lever arm in tanker frame.",
    )
    parser.add_argument("--no-dialog", action="store_true", help="Disable file dialogs when required paths are omitted.")
    return parser.parse_args()


def maybe_dialog_paths(args: argparse.Namespace) -> argparse.Namespace:
    if args.no_dialog or (args.probe_csv and args.tanker_csv and args.novatel_txt):
        return args
    try:
        from tkinter import Tk, filedialog
        root = Tk()
        root.withdraw()
        if args.probe_csv is None:
            args.probe_csv = Path(filedialog.askopenfilename(title="Select probe/receiver navcalcs CSV", filetypes=[("CSV", "*.csv"), ("All files", "*.*")]))
        if args.tanker_csv is None:
            args.tanker_csv = Path(filedialog.askopenfilename(title="Select tanker/target navcalcs CSV", filetypes=[("CSV", "*.csv"), ("All files", "*.*")]))
        if args.novatel_txt is None:
            args.novatel_txt = Path(filedialog.askopenfilename(title="Select NovAtel / TSPI text file", filetypes=[("Text", "*.txt *.dat *.csv"), ("All files", "*.*")]))
        root.destroy()
    except Exception:
        return args
    return args


def main() -> None:
    args = maybe_dialog_paths(parse_args())
    if args.probe_csv is None or args.tanker_csv is None or args.novatel_txt is None:
        raise SystemExit("Provide --probe-csv, --tanker-csv, and --novatel-txt, or run without --no-dialog.")

    probe_csv = Path(args.probe_csv)
    tanker_csv = Path(args.tanker_csv)
    novatel_txt = Path(args.novatel_txt)
    out = args.out or Path(f"truth_compare_{probe_csv.stem}_{tanker_csv.stem}")
    plots_dir = out / "plots"
    tables_dir = out / "tables"
    ensure_dir(out)
    ensure_dir(plots_dir)
    ensure_dir(tables_dir)

    receiver_probe_to_antenna = np.asarray(args.receiver_probe_to_antenna, dtype=float)
    tanker_center_to_antenna = np.asarray(args.tanker_center_to_antenna, dtype=float)
    truth_transform = np.asarray(args.truth_transform, dtype=float).reshape(3, 3) if args.truth_transform is not None else None

    probe = load_navcalcs(probe_csv)
    tanker = load_navcalcs(tanker_csv)
    tspi = load_novatel_tspi(novatel_txt)

    merged = merge_probe_tanker_truth(probe, tanker, tspi, sync_tolerance=float(args.sync_tolerance))
    methods = [m for m in METHODS if method_available_in_merged(merged, m)]
    if not methods:
        raise RuntimeError("No complete pose methods found after merging probe/tanker navcalcs files.")

    merged = compute_vision_vectors(merged, methods, receiver_probe_to_antenna, tanker_center_to_antenna)
    merged = add_truth_vectors(merged, truth_transform)
    chosen_sign, sign_diag = choose_truth_sign(merged, methods, str(args.truth_sign))
    merged = add_errors(merged, methods, chosen_sign)
    err_summary = summarize_truth_errors(merged, methods)

    merged.to_csv(tables_dir / "merged_truth_comparison.csv", index=False)
    err_summary.to_csv(tables_dir / "truth_error_summary.csv", index=False)
    sign_diag.to_csv(tables_dir / "truth_sign_diagnostic.csv", index=False)
    write_markdown_table(err_summary, tables_dir / "truth_error_summary.md")
    write_markdown_table(sign_diag, tables_dir / "truth_sign_diagnostic.md")

    plot_tracking(merged, methods, plots_dir)
    plot_errors(merged, methods, plots_dir)
    plot_summary_bars(err_summary, plots_dir)

    summary_text = build_summary_text(
        probe_csv=probe_csv,
        tanker_csv=tanker_csv,
        novatel_txt=novatel_txt,
        df=merged,
        methods=methods,
        truth_sign=chosen_sign,
        sign_diag=sign_diag,
        err_summary=err_summary,
        sync_tolerance=float(args.sync_tolerance),
    )
    (out / "summary.txt").write_text(summary_text, encoding="utf-8")
    print(summary_text)
    print(f"\nWrote truth comparison to: {out}")


if __name__ == "__main__":
    main()
