"""
Compare probe/tanker navcalcs pose estimates against NovAtel / TSPI truth,
including SE(3) factor-graph smoothed pose outputs.

This is the range-safe comparison script.

Why range-safe?
----------------
The NovAtel / TSPI truth file gives a relative vector in its own coordinate
convention. For the current flight-analysis use case, the TSPI vector magnitude
is valid, but its x/y/z components are not directly comparable with the camera /
pose-estimator axes. Therefore, this script compares all pose methods to truth
using only vector magnitude / range.

Full x/y/z vector comparisons are still produced between vision-derived methods,
because those quantities live in the same internal pose-estimator convention after
probe/tanker synchronization.

Inputs
------
1. Probe / receiver navcalcs CSV generated by the pose pipeline.
2. Tanker / target navcalcs CSV generated by the pose pipeline.
3. Whitespace-delimited NovAtel / TSPI text file containing relative base-to-rover
   ECEF vector columns.

Outputs
-------
The output directory contains:

  plots/
    - truth range overlays and range-error plots
    - raw method vs its own SE(3) factor graph plots
    - all FG vs all FG plots
    - pairwise method comparison plots
    - sigma / 3-sigma range-error plots when covariance information exists
    - scatter, histogram, and smoothness plots
    - each plot written as both PNG and vector PDF

  tables/
    - merged_truth_comparison.csv
    - truth_range_error_summary.csv
    - pairwise_vector_summary.csv
    - pairwise_pose_summary.csv
    - raw_vs_own_fg_summary.csv
    - smoothness_summary.csv
    - method_availability_summary.csv

Example
-------
python truth_compare_navcalcs.py \
    --probe-csv navcalcs_PROBE_BothContext_01062024_0_3M.csv \
    --tanker-csv navcalcs_GIII_Pseudo.csv \
    --novatel-txt relative_tspi.txt \
    --out truth_compare_probe_tanker_fg

Notes
-----
- image_time in navcalcs is converted to GPS seconds when it appears to be Unix
  epoch time. This preserves the previous script's sync behavior.
- Truth x/y/z component plots are intentionally not generated by default.
- Lever arms are applied before forming the antenna-to-antenna vision vector.
"""

from __future__ import annotations

import argparse
import itertools
import math
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, Sequence

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib import colors as mcolors
import numpy as np
import pandas as pd
import warnings
from pandas.errors import PerformanceWarning
warnings.simplefilter("ignore", PerformanceWarning)

PLOT_DPI = 160
LITERATURE_STYLE = {
    "font.family": "serif",
    "font.size": 10,
    "axes.titlesize": 12,
    "axes.labelsize": 10,
    "axes.titleweight": "semibold",
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.grid": True,
    "grid.alpha": 0.22,
    "grid.linewidth": 0.6,
    "grid.linestyle": "--",
    "legend.frameon": False,
    "legend.fontsize": 9,
    "figure.facecolor": "white",
    "axes.facecolor": "white",
    "savefig.facecolor": "white",
    "pdf.fonttype": 42,
    "ps.fonttype": 42,
}
BASE_METHOD_COLORS: dict[str, str] = {
    "pnp": "#1f77b4",
    "qnp": "#2ca02c",
    "wqnp_yolo": "#ff7f0e",
    "wqnp_kfest": "#d62728",
}
FAMILY_SHADE_OFFSETS: dict[str, float] = {
    "raw": -0.08,
    "fg": 0.28,
}
FAMILY_LINESTYLES: dict[str, str] = {
    "raw": "-",
    "fg": "--",
}
FAMILY_MARKERS: dict[str, str] = {
    "raw": "o",
    "fg": "s",
}
TRUTH_COLOR = "#111111"
REFERENCE_COLOR = "#6e6e6e"


# -----------------------------------------------------------------------------
# Method definitions
# -----------------------------------------------------------------------------

@dataclass(frozen=True)
class PoseSpec:
    """Description of one pose source in a navcalcs CSV."""

    key: str
    base_key: str
    label: str
    family: str  # "raw" or "fg"
    valid_col: str
    q_cols: tuple[str, str, str, str]
    t_cols: tuple[str, str, str]
    sigma_t_cols: tuple[str, str, str] | None = None
    cov6_col: str | None = None
    native_range_col: str | None = None
    measurement_count_col: str | None = None
    solver_status_col: str | None = None


BASE_METHODS: tuple[tuple[str, str], ...] = (
    ("pnp", "OpenCV SolvePnP"),
    ("qnp", "SolveQnP"),
    ("wqnp_yolo", "wQnP, YOLO centers + KF covariance"),
    ("wqnp_kfest", "wQnP, KF centers + KF covariance"),
)


def build_pose_specs() -> tuple[PoseSpec, ...]:
    specs: list[PoseSpec] = []
    for base_key, base_label in BASE_METHODS:
        specs.append(
            PoseSpec(
                key=base_key,
                base_key=base_key,
                label=base_label,
                family="raw",
                valid_col=f"{base_key}_valid",
                q_cols=(f"{base_key}_qw", f"{base_key}_qx", f"{base_key}_qy", f"{base_key}_qz"),
                t_cols=(f"{base_key}_tvec_x", f"{base_key}_tvec_y", f"{base_key}_tvec_z"),
                cov6_col=f"{base_key}_cov6",
            )
        )
        specs.append(
            PoseSpec(
                key=f"{base_key}_fg",
                base_key=base_key,
                label=f"{base_label} FG smooth",
                family="fg",
                valid_col=f"{base_key}_fg_valid",
                q_cols=(f"{base_key}_fg_qw", f"{base_key}_fg_qx", f"{base_key}_fg_qy", f"{base_key}_fg_qz"),
                t_cols=(f"{base_key}_fg_tvec_x", f"{base_key}_fg_tvec_y", f"{base_key}_fg_tvec_z"),
                sigma_t_cols=(f"{base_key}_fg_sigma_x", f"{base_key}_fg_sigma_y", f"{base_key}_fg_sigma_z"),
                cov6_col=f"{base_key}_fg_cov6",
                native_range_col=f"{base_key}_fg_range",
                measurement_count_col=f"{base_key}_fg_measurement_count",
                solver_status_col=f"{base_key}_fg_solver_status",
            )
        )
    return tuple(specs)


POSE_SPECS: tuple[PoseSpec, ...] = build_pose_specs()

DEFAULT_RECEIVER_PROBE_TO_ANTENNA = np.array([-8.42027, 0.45487, 0.67881], dtype=float)
DEFAULT_TANKER_CENTER_TO_ANTENNA = np.array([7.78935, -0.00469, -0.06247], dtype=float)
GPS_WEEK_SECONDS = 604800.0
UNIX_TO_GPS_EPOCH_SECONDS = (
    datetime(1980, 1, 6, tzinfo=timezone.utc) - datetime(1970, 1, 1, tzinfo=timezone.utc)
).total_seconds()
GPS_MINUS_UTC_LEAP_SECONDS = 18.0


def setup_matplotlib_style() -> None:
    plt.rcParams.update(LITERATURE_STYLE)


def tint_color(color: str, amount: float) -> str:
    rgb = np.array(mcolors.to_rgb(color), dtype=float)
    amount = float(np.clip(amount, -1.0, 1.0))
    if amount >= 0.0:
        mixed = rgb + (1.0 - rgb) * amount
    else:
        mixed = rgb * (1.0 + amount)
    return mcolors.to_hex(np.clip(mixed, 0.0, 1.0))


def method_style(spec: PoseSpec) -> dict[str, object]:
    base = BASE_METHOD_COLORS.get(spec.base_key, "#4c4c4c")
    color = tint_color(base, FAMILY_SHADE_OFFSETS.get(spec.family, 0.0))
    return {
        "color": color,
        "linestyle": FAMILY_LINESTYLES.get(spec.family, "-"),
    }


def method_marker(spec: PoseSpec) -> str:
    return FAMILY_MARKERS.get(spec.family, "o")


def pair_style(a: PoseSpec, b: PoseSpec) -> dict[str, object]:
    color_a = np.array(mcolors.to_rgb(method_style(a)["color"]), dtype=float)
    color_b = np.array(mcolors.to_rgb(method_style(b)["color"]), dtype=float)
    mixed = mcolors.to_hex(np.clip(0.5 * (color_a + color_b), 0.0, 1.0))
    linestyle = "--" if a.family != b.family else "-"
    return {"color": mixed, "linestyle": linestyle}


def style_axes(ax: plt.Axes) -> None:
    ax.grid(True, which="major", axis="both")
    ax.set_axisbelow(True)


# -----------------------------------------------------------------------------
# Basic helpers
# -----------------------------------------------------------------------------

def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def have_cols(df: pd.DataFrame, cols: Iterable[str]) -> bool:
    return all(c in df.columns for c in cols)


def suffixed(col: str, suffix: str) -> str:
    return f"{col}_{suffix}"


def spec_cols(spec: PoseSpec, suffix: str) -> tuple[str, tuple[str, ...], tuple[str, ...]]:
    return (
        suffixed(spec.valid_col, suffix),
        tuple(suffixed(c, suffix) for c in spec.q_cols),
        tuple(suffixed(c, suffix) for c in spec.t_cols),
    )


def sanitize_name(text: str) -> str:
    text = text.replace("+", "plus").replace("-", "minus")
    return re.sub(r"[^A-Za-z0-9_.]+", "_", text).strip("_")


def as_bool(series: pd.Series) -> np.ndarray:
    if series.dtype == bool:
        return series.fillna(False).to_numpy(dtype=bool)
    if pd.api.types.is_numeric_dtype(series):
        return (series.fillna(0).astype(float) != 0.0).to_numpy(dtype=bool)
    true_values = {"true", "t", "1", "yes", "y", "valid"}
    return series.fillna("false").astype(str).str.strip().str.lower().isin(true_values).to_numpy(dtype=bool)


def numeric(df: pd.DataFrame, cols: Iterable[str]) -> np.ndarray:
    return df.loc[:, list(cols)].apply(pd.to_numeric, errors="coerce").to_numpy(dtype=float)


def numeric_series(df: pd.DataFrame, col: str, default: float = np.nan) -> np.ndarray:
    if col not in df.columns:
        return np.full(len(df), default, dtype=float)
    return pd.to_numeric(df[col], errors="coerce").to_numpy(dtype=float)


def finite_rows(arr: np.ndarray) -> np.ndarray:
    return np.all(np.isfinite(arr), axis=1)


def vector_norm(arr: np.ndarray) -> np.ndarray:
    return np.linalg.norm(arr, axis=1)


def finite_stats(values: np.ndarray | pd.Series) -> dict[str, float | int]:
    arr = np.asarray(values, dtype=float)
    arr = arr[np.isfinite(arr)]
    if arr.size == 0:
        return {
            "count": 0,
            "mean": np.nan,
            "median": np.nan,
            "std": np.nan,
            "rmse": np.nan,
            "mae": np.nan,
            "p05": np.nan,
            "p25": np.nan,
            "p75": np.nan,
            "p95": np.nan,
            "max_abs": np.nan,
        }
    return {
        "count": int(arr.size),
        "mean": float(np.mean(arr)),
        "median": float(np.median(arr)),
        "std": float(np.std(arr, ddof=1)) if arr.size > 1 else 0.0,
        "rmse": float(np.sqrt(np.mean(arr ** 2))),
        "mae": float(np.mean(np.abs(arr))),
        "p05": float(np.percentile(arr, 5)),
        "p25": float(np.percentile(arr, 25)),
        "p75": float(np.percentile(arr, 75)),
        "p95": float(np.percentile(arr, 95)),
        "max_abs": float(np.max(np.abs(arr))),
    }


def append_stats(row: dict[str, object], prefix: str, values: np.ndarray | pd.Series) -> None:
    stats = finite_stats(values)
    for key, value in stats.items():
        row[f"{prefix}_{key}"] = value


def write_markdown_table(df: pd.DataFrame, path: Path, float_fmt: str = ".5g") -> None:
    def fmt(x: object) -> str:
        if isinstance(x, (float, np.floating)):
            if math.isnan(float(x)):
                return ""
            return format(float(x), float_fmt)
        return str(x)

    cols = list(df.columns)
    lines = ["| " + " | ".join(cols) + " |", "| " + " | ".join(["---"] * len(cols)) + " |"]
    for _, row in df.iterrows():
        lines.append("| " + " | ".join(fmt(row[c]) for c in cols) + " |")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def elapsed_time_axis(df: pd.DataFrame) -> tuple[np.ndarray, str]:
    if "elapsed_s" in df.columns:
        return df["elapsed_s"].to_numpy(dtype=float), "Elapsed synchronized time (s)"
    if "sync_time_s" in df.columns:
        t = df["sync_time_s"].to_numpy(dtype=float)
        return t - np.nanmin(t), "Elapsed synchronized time (s)"
    raise KeyError("No usable plot time column found.")


def unix_to_gps_seconds(unix_seconds: np.ndarray) -> np.ndarray:
    """Convert Unix UTC seconds to GPS seconds on the continuous GPS timescale."""
    return np.asarray(unix_seconds, dtype=float) - UNIX_TO_GPS_EPOCH_SECONDS + GPS_MINUS_UTC_LEAP_SECONDS


def prepare_navcalcs_sync_time(df: pd.DataFrame) -> pd.DataFrame:
    """Add GPS-compatible synchronization columns derived from image_time."""
    out = df.copy()
    image_time = out["image_time"].to_numpy(dtype=float)

    # Navcalcs image_time is often Unix epoch seconds. If it is not epoch-sized,
    # treat it as already GPS-relative / experiment-relative.
    if np.nanmedian(image_time) > 1.0e9:
        sync_time = unix_to_gps_seconds(image_time)
    else:
        sync_time = image_time

    out["sync_time_s"] = sync_time
    out["sync_gps_week"] = np.floor(sync_time / GPS_WEEK_SECONDS)
    out["sync_gps_tow"] = sync_time - out["sync_gps_week"] * GPS_WEEK_SECONDS
    return out


# -----------------------------------------------------------------------------
# Quaternion / rotation helpers
# -----------------------------------------------------------------------------

def quat_to_rotmat_batch(q: np.ndarray) -> np.ndarray:
    """Return R(q) for scalar-first quaternions, row-wise.

    The returned rotation maps object-frame vectors into the camera / estimator
    frame under the convention used by the navcalcs pose output.
    """
    q = q.astype(float)
    n = np.linalg.norm(q, axis=1, keepdims=True)
    n[n == 0.0] = np.nan
    q = q / n

    w, x, y, z = q[:, 0], q[:, 1], q[:, 2], q[:, 3]
    R = np.empty((len(q), 3, 3), dtype=float)

    R[:, 0, 0] = 1.0 - 2.0 * (y * y + z * z)
    R[:, 0, 1] = 2.0 * (x * y - z * w)
    R[:, 0, 2] = 2.0 * (x * z + y * w)

    R[:, 1, 0] = 2.0 * (x * y + z * w)
    R[:, 1, 1] = 1.0 - 2.0 * (x * x + z * z)
    R[:, 1, 2] = 2.0 * (y * z - x * w)

    R[:, 2, 0] = 2.0 * (x * z - y * w)
    R[:, 2, 1] = 2.0 * (y * z + x * w)
    R[:, 2, 2] = 1.0 - 2.0 * (x * x + y * y)
    return R


def rotate_vectors_batch(R: np.ndarray, v: np.ndarray) -> np.ndarray:
    return np.einsum("nij,j->ni", R, v)


def quat_angle_deg_batch(q_a: np.ndarray, q_b: np.ndarray) -> np.ndarray:
    """Shortest angular separation between scalar-first unit quaternions."""
    q_a = q_a.astype(float)
    q_b = q_b.astype(float)
    na = np.linalg.norm(q_a, axis=1)
    nb = np.linalg.norm(q_b, axis=1)
    denom = na * nb
    dot = np.sum(q_a * q_b, axis=1)
    out = np.full(len(q_a), np.nan, dtype=float)
    good = np.isfinite(dot) & np.isfinite(denom) & (denom > 0.0)
    d = np.clip(np.abs(dot[good] / denom[good]), -1.0, 1.0)
    out[good] = np.rad2deg(2.0 * np.arccos(d))
    return out


# -----------------------------------------------------------------------------
# Loading and synchronization
# -----------------------------------------------------------------------------

def load_navcalcs(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    if "image_time" not in df.columns:
        raise ValueError(f"{path} does not contain an image_time column.")
    df = df.copy()
    df["image_time"] = pd.to_numeric(df["image_time"], errors="coerce")
    df = df[np.isfinite(df["image_time"])].sort_values("image_time").reset_index(drop=True)
    return prepare_navcalcs_sync_time(df)


def load_novatel_tspi(path: Path) -> pd.DataFrame:
    """Load whitespace-delimited 28-column TSPI/DGPS data.

    Column mapping follows the user-provided header table used in the prior
    script:
      1  GPS time of week
      5  Vector Base to Rover ECEF-X Location
      7  Vector Base to Rover ECEF-Y Location
      9  Vector Base to Rover ECEF-Z Location
      28 GPS week
    """
    df = pd.read_csv(path, sep=r"\s+", header=None, comment="#", engine="python")
    if df.shape[1] < 28:
        raise ValueError(f"Expected at least 28 TSPI columns; found {df.shape[1]} in {path}")

    names = [
        "gps_tow",
        "rover_ecef_x", "rover_ecef_y", "rover_ecef_z",
        "base_to_rover_ecef_x", "base_to_rover_ecef_x_std",
        "base_to_rover_ecef_y", "base_to_rover_ecef_y_std",
        "base_to_rover_ecef_z", "base_to_rover_ecef_z_std",
        "ecef_vx", "ecef_vx_std",
        "ecef_vy", "ecef_vy_std",
        "ecef_vz", "ecef_vz_std",
        "gps_satellites", "quality_number", "ddop", "ca_rms", "l1_rms", "double_difference_dop",
        "fwd_rev_sep_east", "fwd_rev_sep_north", "fwd_rev_sep_height",
        "forward_combined_weighting", "reverse_combined_weighting", "gps_week",
    ]
    out = df.iloc[:, :28].copy()
    out.columns = names
    for c in out.columns:
        out[c] = pd.to_numeric(out[c], errors="coerce")
    out["truth_sync_time_s"] = out["gps_week"] * GPS_WEEK_SECONDS + out["gps_tow"]
    out = out[np.isfinite(out["truth_sync_time_s"])].sort_values("truth_sync_time_s").reset_index(drop=True)
    return out


def suffix_navcalcs_columns(df: pd.DataFrame, suffix: str, sync_key_name: str) -> pd.DataFrame:
    """Suffix all navcalcs columns while preserving one synchronization key."""
    rename: dict[str, str] = {}
    for col in df.columns:
        if col == "sync_time_s":
            rename[col] = sync_key_name
        else:
            rename[col] = suffixed(col, suffix)
    return df.rename(columns=rename)


def merge_probe_tanker_truth(
    probe: pd.DataFrame,
    tanker: pd.DataFrame,
    tspi: pd.DataFrame,
    sync_tolerance: float,
) -> pd.DataFrame:
    probe_pref = suffix_navcalcs_columns(probe.sort_values("sync_time_s").reset_index(drop=True), "probe", "sync_time_s")
    tanker_pref = suffix_navcalcs_columns(tanker.sort_values("sync_time_s").reset_index(drop=True), "tanker", "sync_time_s_tanker")
    tspi = tspi.sort_values("truth_sync_time_s").reset_index(drop=True)

    merged = pd.merge_asof(
        probe_pref.sort_values("sync_time_s"),
        tanker_pref.sort_values("sync_time_s_tanker"),
        left_on="sync_time_s",
        right_on="sync_time_s_tanker",
        direction="nearest",
        tolerance=sync_tolerance,
    )
    merged["tanker_time_error_s"] = merged["sync_time_s"] - merged["sync_time_s_tanker"]

    merged = pd.merge_asof(
        merged.sort_values("sync_time_s"),
        tspi,
        left_on="sync_time_s",
        right_on="truth_sync_time_s",
        direction="nearest",
        tolerance=sync_tolerance,
    )
    merged["truth_time_error_s"] = merged["sync_time_s"] - merged["truth_sync_time_s"]
    t = merged["sync_time_s"].to_numpy(dtype=float)
    merged["elapsed_s"] = t - np.nanmin(t)
    return merged.reset_index(drop=True)


# -----------------------------------------------------------------------------
# Covariance / sigma helpers
# -----------------------------------------------------------------------------

def parse_cov6_translation_sigmas_cell(cell: object) -> np.ndarray:
    """Return sqrt of the first 3 diagonal entries from a serialized 6x6 covariance."""
    if cell is None or (isinstance(cell, float) and math.isnan(cell)):
        return np.array([np.nan, np.nan, np.nan], dtype=float)
    text = str(cell).strip()
    if not text:
        return np.array([np.nan, np.nan, np.nan], dtype=float)
    try:
        arr = np.fromstring(text.replace(";", ","), sep=",")
        if arr.size == 36:
            M = arr.reshape(6, 6)
            diag = np.diag(M)[:3]
        elif arr.size >= 6:
            # Some pipelines serialize only diagonal covariance terms.
            diag = arr[:3]
        else:
            return np.array([np.nan, np.nan, np.nan], dtype=float)
        diag = np.where(diag >= 0.0, diag, np.nan)
        return np.sqrt(diag)
    except Exception:
        return np.array([np.nan, np.nan, np.nan], dtype=float)


def pose_translation_sigmas(df: pd.DataFrame, spec: PoseSpec, suffix: str) -> np.ndarray:
    """Return per-row translational sigma for one pose/object if available.

    Preference order matters.  Raw QnP-family poses may have both the original
    local solver covariance, e.g. qnp_cov6, and the truth-diagnostic effective
    covariance written by the SE(3) smoother, e.g. qnp_cov6_effective.  For
    truth-range coverage plots, use the effective raw covariance first when it
    exists; otherwise fall back to the original covariance so older CSVs still
    plot.
    """

    # Fast path: explicit sigma columns.  FG poses already have these.  Raw
    # poses get *_sigma_x_effective columns when the smoother appends raw
    # effective covariance diagnostics.
    sigma_candidates: list[tuple[str, str, str]] = []
    if spec.family == "raw":
        sigma_candidates.append(
            (
                f"{spec.base_key}_sigma_x_effective",
                f"{spec.base_key}_sigma_y_effective",
                f"{spec.base_key}_sigma_z_effective",
            )
        )
    if spec.sigma_t_cols is not None:
        sigma_candidates.append(spec.sigma_t_cols)

    for cols in sigma_candidates:
        sigma_cols = tuple(suffixed(c, suffix) for c in cols)
        if have_cols(df, sigma_cols):
            sig = numeric(df, sigma_cols)
            if np.any(np.isfinite(sig)):
                return sig

    # Slower path: parse covariance strings.  Prefer raw *_cov6_effective over
    # raw *_cov6; the latter is the local Hessian/solver covariance and is often
    # intentionally overconfident for truth-level coverage.
    cov_candidates: list[str] = []
    if spec.family == "raw":
        cov_candidates.append(f"{spec.base_key}_cov6_effective")
    if spec.cov6_col is not None:
        cov_candidates.append(spec.cov6_col)

    for cov_base_col in cov_candidates:
        cov_col = suffixed(cov_base_col, suffix)
        if cov_col in df.columns:
            vals = [parse_cov6_translation_sigmas_cell(v) for v in df[cov_col].to_numpy()]
            sig = np.vstack(vals) if vals else np.full((len(df), 3), np.nan)
            if np.any(np.isfinite(sig)):
                return sig

    return np.full((len(df), 3), np.nan, dtype=float)


# -----------------------------------------------------------------------------
# Vision vector reconstruction and truth-range comparison
# -----------------------------------------------------------------------------

def spec_available_for_object(df: pd.DataFrame, spec: PoseSpec, suffix: str) -> bool:
    valid_col, q_cols, t_cols = spec_cols(spec, suffix)
    return have_cols(df, [valid_col, *q_cols, *t_cols])


def spec_available_for_vector(df: pd.DataFrame, spec: PoseSpec) -> bool:
    return spec_available_for_object(df, spec, "probe") and spec_available_for_object(df, spec, "tanker")


def pose_arrays(df: pd.DataFrame, spec: PoseSpec, suffix: str) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    valid_col, q_cols, t_cols = spec_cols(spec, suffix)
    q = numeric(df, q_cols)
    t = numeric(df, t_cols)
    valid = as_bool(df[valid_col]) & finite_rows(q) & finite_rows(t)
    return q, t, valid


def compute_vision_vectors(
    df: pd.DataFrame,
    specs: Sequence[PoseSpec],
    receiver_probe_to_antenna: np.ndarray,
    tanker_center_to_antenna: np.ndarray,
) -> pd.DataFrame:
    out = df.copy()

    for spec in specs:
        q_probe, t_probe, valid_probe = pose_arrays(out, spec, "probe")
        q_tanker, t_tanker, valid_tanker = pose_arrays(out, spec, "tanker")

        R_probe = quat_to_rotmat_batch(q_probe)
        R_tanker = quat_to_rotmat_batch(q_tanker)

        p_receiver_ant = t_probe + rotate_vectors_batch(R_probe, receiver_probe_to_antenna)
        p_tanker_ant = t_tanker + rotate_vectors_batch(R_tanker, tanker_center_to_antenna)
        vision_vec = p_tanker_ant - p_receiver_ant

        valid = valid_probe & valid_tanker & finite_rows(p_receiver_ant) & finite_rows(p_tanker_ant) & finite_rows(vision_vec)

        for i, axis in enumerate("xyz"):
            out[f"{spec.key}_receiver_ant_{axis}"] = p_receiver_ant[:, i]
            out[f"{spec.key}_tanker_ant_{axis}"] = p_tanker_ant[:, i]
            out[f"{spec.key}_vision_vec_{axis}"] = vision_vec[:, i]
        out[f"{spec.key}_vision_range"] = vector_norm(vision_vec)
        out[f"{spec.key}_truth_compare_valid"] = valid

        # Range sigma from translational sigmas only. This deliberately ignores
        # lever-arm orientation covariance; it is still useful as a conservative
        # diagnostic when FG translational covariance is the dominant term.
        sig_probe = pose_translation_sigmas(out, spec, "probe")
        sig_tanker = pose_translation_sigmas(out, spec, "tanker")
        vec_var_diag = sig_probe ** 2 + sig_tanker ** 2
        rng = out[f"{spec.key}_vision_range"].to_numpy(dtype=float)
        unit = np.full_like(vision_vec, np.nan, dtype=float)
        good_rng = np.isfinite(rng) & (rng > 0.0)
        unit[good_rng] = vision_vec[good_rng] / rng[good_rng, None]
        range_var = np.sum((unit ** 2) * vec_var_diag, axis=1)
        range_sigma = np.sqrt(np.where(range_var >= 0.0, range_var, np.nan))
        range_sigma[~valid] = np.nan
        out[f"{spec.key}_range_sigma"] = range_sigma
        out[f"{spec.key}_range_3sigma"] = 3.0 * range_sigma

    return out


def add_truth_range(df: pd.DataFrame, truth_transform: np.ndarray | None) -> pd.DataFrame:
    out = df.copy()
    truth = numeric(out, ["base_to_rover_ecef_x", "base_to_rover_ecef_y", "base_to_rover_ecef_z"])
    if truth_transform is not None:
        truth = truth @ truth_transform.T
    for i, axis in enumerate("xyz"):
        out[f"truth_vector_{axis}"] = truth[:, i]
    out["truth_range"] = vector_norm(truth)
    out["truth_range_valid"] = np.isfinite(out["truth_range"].to_numpy(dtype=float))
    return out


def add_truth_range_errors(df: pd.DataFrame, specs: Sequence[PoseSpec]) -> pd.DataFrame:
    out = df.copy()
    truth_range = out["truth_range"].to_numpy(dtype=float)
    truth_valid = out["truth_range_valid"].to_numpy(dtype=bool)

    for spec in specs:
        method_range = out[f"{spec.key}_vision_range"].to_numpy(dtype=float)
        valid = out[f"{spec.key}_truth_compare_valid"].to_numpy(dtype=bool) & truth_valid & np.isfinite(method_range)
        err = method_range - truth_range
        out[f"{spec.key}_range_error"] = np.where(valid, err, np.nan)
        out[f"{spec.key}_abs_range_error"] = np.abs(out[f"{spec.key}_range_error"])
        sig = out[f"{spec.key}_range_sigma"].to_numpy(dtype=float)
        norm = np.full(len(out), np.nan, dtype=float)
        good = valid & np.isfinite(sig) & (sig > 0.0)
        norm[good] = err[good] / sig[good]
        out[f"{spec.key}_normalized_range_error"] = norm
        out[f"{spec.key}_inside_3sigma"] = good & (np.abs(norm) <= 3.0)
    return out


# -----------------------------------------------------------------------------
# Summaries
# -----------------------------------------------------------------------------

def summarize_availability(df: pd.DataFrame, specs: Sequence[PoseSpec]) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    truth_valid = df.get("truth_range_valid", pd.Series(False, index=df.index)).to_numpy(dtype=bool)
    for spec in specs:
        valid_col = f"{spec.key}_truth_compare_valid"
        valid = df[valid_col].to_numpy(dtype=bool) if valid_col in df.columns else np.zeros(len(df), dtype=bool)
        row: dict[str, object] = {
            "method": spec.label,
            "key": spec.key,
            "base_key": spec.base_key,
            "family": spec.family,
            "valid_vector_samples": int(np.sum(valid)),
            "valid_truth_range_samples": int(np.sum(valid & truth_valid)),
            "total_rows": int(len(df)),
            "has_range_sigma": bool(np.any(np.isfinite(df.get(f"{spec.key}_range_sigma", pd.Series(np.nan, index=df.index)).to_numpy(dtype=float)))),
        }
        for suffix in ("probe", "tanker"):
            if spec.measurement_count_col is not None:
                col = suffixed(spec.measurement_count_col, suffix)
                if col in df.columns:
                    vals = numeric_series(df, col)
                    append_stats(row, f"{suffix}_measurement_count", vals)
            if spec.solver_status_col is not None:
                col = suffixed(spec.solver_status_col, suffix)
                if col in df.columns:
                    nonempty = df[col].fillna("").astype(str).str.len() > 0
                    row[f"{suffix}_solver_status_nonempty"] = int(nonempty.sum())
                    status_counts = df.loc[nonempty, col].astype(str).value_counts().head(5)
                    row[f"{suffix}_solver_status_top"] = "; ".join(f"{k}:{v}" for k, v in status_counts.items())
        rows.append(row)
    return pd.DataFrame(rows)


def summarize_truth_range_errors(df: pd.DataFrame, specs: Sequence[PoseSpec]) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for spec in specs:
        valid = df[f"{spec.key}_truth_compare_valid"].to_numpy(dtype=bool) & df["truth_range_valid"].to_numpy(dtype=bool)
        row: dict[str, object] = {
            "method": spec.label,
            "key": spec.key,
            "base_key": spec.base_key,
            "family": spec.family,
            "valid_samples": int(np.sum(valid)),
            "total_rows": int(len(df)),
        }
        append_stats(row, "range_error", df[f"{spec.key}_range_error"])
        append_stats(row, "abs_range_error", df[f"{spec.key}_abs_range_error"])
        append_stats(row, "normalized_range_error", df[f"{spec.key}_normalized_range_error"])
        inside = df[f"{spec.key}_inside_3sigma"].to_numpy(dtype=bool)
        sigma_valid = np.isfinite(df[f"{spec.key}_normalized_range_error"].to_numpy(dtype=float))
        row["sigma_valid_count"] = int(np.sum(sigma_valid))
        row["inside_3sigma_count"] = int(np.sum(inside & sigma_valid))
        row["inside_3sigma_fraction"] = float(np.sum(inside & sigma_valid) / np.sum(sigma_valid)) if np.sum(sigma_valid) else np.nan
        rows.append(row)
    return pd.DataFrame(rows)


def pair_key(a: PoseSpec, b: PoseSpec) -> str:
    return f"{a.key}__minus__{b.key}"


def pair_label(a: PoseSpec, b: PoseSpec) -> str:
    return f"{a.label} - {b.label}"


def add_pairwise_vector_differences(df: pd.DataFrame, specs: Sequence[PoseSpec]) -> pd.DataFrame:
    out = df.copy()
    extra: dict[str, np.ndarray] = {}
    for a, b in itertools.combinations(specs, 2):
        pk = pair_key(a, b)
        va = numeric(out, [f"{a.key}_vision_vec_x", f"{a.key}_vision_vec_y", f"{a.key}_vision_vec_z"])
        vb = numeric(out, [f"{b.key}_vision_vec_x", f"{b.key}_vision_vec_y", f"{b.key}_vision_vec_z"])
        valid = (
            out[f"{a.key}_truth_compare_valid"].to_numpy(dtype=bool)
            & out[f"{b.key}_truth_compare_valid"].to_numpy(dtype=bool)
            & finite_rows(va)
            & finite_rows(vb)
        )
        delta = va - vb
        for i, axis in enumerate("xyz"):
            extra[f"pair_{pk}_vec_delta_{axis}"] = np.where(valid, delta[:, i], np.nan)
        extra[f"pair_{pk}_vector_delta_norm"] = np.where(valid, vector_norm(delta), np.nan)
        range_delta = out[f"{a.key}_vision_range"].to_numpy(dtype=float) - out[f"{b.key}_vision_range"].to_numpy(dtype=float)
        extra[f"pair_{pk}_range_delta"] = np.where(valid, range_delta, np.nan)
        extra[f"pair_{pk}_abs_range_delta"] = np.abs(extra[f"pair_{pk}_range_delta"])
    if extra:
        out = pd.concat([out, pd.DataFrame(extra, index=out.index)], axis=1).copy()
    return out

def summarize_pairwise_vectors(df: pd.DataFrame, specs: Sequence[PoseSpec]) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for a, b in itertools.combinations(specs, 2):
        pk = pair_key(a, b)
        row: dict[str, object] = {
            "pair": pair_label(a, b),
            "a_key": a.key,
            "b_key": b.key,
            "a_family": a.family,
            "b_family": b.family,
            "same_base": a.base_key == b.base_key,
            "comparison_class": comparison_class(a, b),
        }
        append_stats(row, "range_delta", df[f"pair_{pk}_range_delta"])
        append_stats(row, "abs_range_delta", df[f"pair_{pk}_abs_range_delta"])
        append_stats(row, "vector_delta_norm", df[f"pair_{pk}_vector_delta_norm"])
        rows.append(row)
    return pd.DataFrame(rows)


def comparison_class(a: PoseSpec, b: PoseSpec) -> str:
    if a.base_key == b.base_key and {a.family, b.family} == {"raw", "fg"}:
        return "raw_vs_own_fg"
    if a.family == "fg" and b.family == "fg":
        return "fg_vs_fg"
    if a.family == "raw" and b.family == "raw":
        return "raw_vs_raw"
    return "raw_vs_other_fg"


def pose_pair_key(a: PoseSpec, b: PoseSpec, suffix: str) -> str:
    return f"{suffix}_{a.key}__minus__{b.key}"


def add_pairwise_pose_differences(df: pd.DataFrame, specs: Sequence[PoseSpec]) -> pd.DataFrame:
    out = df.copy()
    extra: dict[str, np.ndarray] = {}
    for suffix in ("probe", "tanker"):
        for a, b in itertools.combinations(specs, 2):
            q_a, t_a, valid_a = pose_arrays(out, a, suffix)
            q_b, t_b, valid_b = pose_arrays(out, b, suffix)
            valid = valid_a & valid_b & finite_rows(q_a) & finite_rows(q_b) & finite_rows(t_a) & finite_rows(t_b)
            pk = pose_pair_key(a, b, suffix)
            trans_delta = t_a - t_b
            angle_delta = quat_angle_deg_batch(q_a, q_b)
            extra[f"posepair_{pk}_translation_delta_norm"] = np.where(valid, vector_norm(trans_delta), np.nan)
            extra[f"posepair_{pk}_attitude_delta_deg"] = np.where(valid, angle_delta, np.nan)
            for i, axis in enumerate("xyz"):
                extra[f"posepair_{pk}_translation_delta_{axis}"] = np.where(valid, trans_delta[:, i], np.nan)
    if extra:
        out = pd.concat([out, pd.DataFrame(extra, index=out.index)], axis=1).copy()
    return out

def summarize_pairwise_poses(df: pd.DataFrame, specs: Sequence[PoseSpec]) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for suffix in ("probe", "tanker"):
        for a, b in itertools.combinations(specs, 2):
            pk = pose_pair_key(a, b, suffix)
            row: dict[str, object] = {
                "object": suffix,
                "pair": pair_label(a, b),
                "a_key": a.key,
                "b_key": b.key,
                "a_family": a.family,
                "b_family": b.family,
                "same_base": a.base_key == b.base_key,
                "comparison_class": comparison_class(a, b),
            }
            append_stats(row, "translation_delta_norm", df[f"posepair_{pk}_translation_delta_norm"])
            append_stats(row, "attitude_delta_deg", df[f"posepair_{pk}_attitude_delta_deg"])
            rows.append(row)
    return pd.DataFrame(rows)


def raw_vs_own_fg_pairs(specs: Sequence[PoseSpec]) -> list[tuple[PoseSpec, PoseSpec]]:
    by_key = {s.key: s for s in specs}
    pairs: list[tuple[PoseSpec, PoseSpec]] = []
    for base_key, _ in BASE_METHODS:
        raw = by_key.get(base_key)
        fg = by_key.get(f"{base_key}_fg")
        if raw is not None and fg is not None:
            pairs.append((raw, fg))
    return pairs


def summarize_raw_vs_own_fg(vector_summary: pd.DataFrame, pose_summary: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    v = vector_summary[vector_summary["comparison_class"] == "raw_vs_own_fg"].copy()
    p = pose_summary[pose_summary["comparison_class"] == "raw_vs_own_fg"].copy()
    for _, row in v.iterrows():
        base = row["a_key"] if str(row["a_family"]) == "raw" else row["b_key"].replace("_fg", "")
        out: dict[str, object] = {
            "base_key": base,
            "pair": row["pair"],
            "range_delta_rmse": row.get("range_delta_rmse", np.nan),
            "range_delta_median": row.get("range_delta_median", np.nan),
            "abs_range_delta_median": row.get("abs_range_delta_median", np.nan),
            "vector_delta_norm_median": row.get("vector_delta_norm_median", np.nan),
            "vector_delta_norm_p95": row.get("vector_delta_norm_p95", np.nan),
        }
        for obj in ("probe", "tanker"):
            match = p[(p["object"] == obj) & (p["a_key"].isin([base, f"{base}_fg"])) & (p["b_key"].isin([base, f"{base}_fg"]))]
            if not match.empty:
                m = match.iloc[0]
                out[f"{obj}_translation_delta_norm_median"] = m.get("translation_delta_norm_median", np.nan)
                out[f"{obj}_translation_delta_norm_p95"] = m.get("translation_delta_norm_p95", np.nan)
                out[f"{obj}_attitude_delta_deg_median"] = m.get("attitude_delta_deg_median", np.nan)
                out[f"{obj}_attitude_delta_deg_p95"] = m.get("attitude_delta_deg_p95", np.nan)
        rows.append(out)
    return pd.DataFrame(rows)


def summarize_smoothness(df: pd.DataFrame, specs: Sequence[PoseSpec]) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    t = df["elapsed_s"].to_numpy(dtype=float)
    for spec in specs:
        valid = df[f"{spec.key}_truth_compare_valid"].to_numpy(dtype=bool)
        rng = df[f"{spec.key}_vision_range"].to_numpy(dtype=float)
        vec = numeric(df, [f"{spec.key}_vision_vec_x", f"{spec.key}_vision_vec_y", f"{spec.key}_vision_vec_z"])

        row: dict[str, object] = {
            "method": spec.label,
            "key": spec.key,
            "base_key": spec.base_key,
            "family": spec.family,
            "valid_samples": int(np.sum(valid)),
        }

        idx = np.where(valid & np.isfinite(t) & np.isfinite(rng) & finite_rows(vec))[0]
        if idx.size >= 2:
            dt = np.diff(t[idx])
            dr = np.diff(rng[idx])
            dv = np.diff(vec[idx], axis=0)
            good_dt = np.isfinite(dt) & (dt > 0.0)
            range_rate = np.full_like(dr, np.nan, dtype=float)
            vector_rate_norm = np.full_like(dr, np.nan, dtype=float)
            range_rate[good_dt] = dr[good_dt] / dt[good_dt]
            vector_rate_norm[good_dt] = vector_norm(dv[good_dt]) / dt[good_dt]
            append_stats(row, "range_step", dr)
            append_stats(row, "abs_range_step", np.abs(dr))
            append_stats(row, "range_rate", range_rate)
            append_stats(row, "abs_range_rate", np.abs(range_rate))
            append_stats(row, "vector_step_norm", vector_norm(dv))
            append_stats(row, "vector_rate_norm", vector_rate_norm)
        else:
            for name in ["range_step", "abs_range_step", "range_rate", "abs_range_rate", "vector_step_norm", "vector_rate_norm"]:
                append_stats(row, name, np.array([], dtype=float))
        rows.append(row)
    return pd.DataFrame(rows)


# -----------------------------------------------------------------------------
# Plotting helpers
# -----------------------------------------------------------------------------

def savefig(path: Path) -> None:
    plt.tight_layout()
    if path.suffix.lower() != ".pdf":
        plt.savefig(path, dpi=PLOT_DPI)
        plt.savefig(path.with_suffix(".pdf"))
    else:
        plt.savefig(path)
    plt.close()


def plot_specs_for_family(specs: Sequence[PoseSpec], family: str | None) -> list[PoseSpec]:
    if family is None:
        return list(specs)
    return [s for s in specs if s.family == family]


def plot_truth_range_tracking(df: pd.DataFrame, specs: Sequence[PoseSpec], out_dir: Path) -> None:
    x, xlabel = elapsed_time_axis(df)
    for family, filename, title_suffix in [
        (None, "truth_range_tracking_all_methods.png", "all methods"),
        ("raw", "truth_range_tracking_raw_methods.png", "raw methods"),
        ("fg", "truth_range_tracking_fg_methods.png", "SE(3) factor graphs"),
    ]:
        subset = plot_specs_for_family(specs, family)
        if not subset:
            continue
        plt.figure(figsize=(12, 6))
        ax = plt.gca()
        plt.plot(x, df["truth_range"], linewidth=2.2, color=TRUTH_COLOR, label="NovAtel / TSPI truth magnitude")
        for spec in subset:
            y = df[f"{spec.key}_vision_range"].where(df[f"{spec.key}_truth_compare_valid"], np.nan)
            plt.plot(x, y, linewidth=1.5, label=spec.label, **method_style(spec))
        plt.xlabel(xlabel)
        plt.ylabel("Antenna-to-antenna vector magnitude")
        plt.title(f"Truth-range tracking: {title_suffix}")
        style_axes(ax)
        plt.legend()
        savefig(out_dir / filename)


def plot_truth_range_errors(df: pd.DataFrame, specs: Sequence[PoseSpec], out_dir: Path) -> None:
    x, xlabel = elapsed_time_axis(df)
    for family, filename, title_suffix in [
        (None, "truth_range_error_all_methods.png", "all methods"),
        ("raw", "truth_range_error_raw_methods.png", "raw methods"),
        ("fg", "truth_range_error_fg_methods.png", "SE(3) factor graphs"),
    ]:
        subset = plot_specs_for_family(specs, family)
        if not subset:
            continue
        plt.figure(figsize=(12, 6))
        ax = plt.gca()
        for spec in subset:
            plt.plot(x, df[f"{spec.key}_range_error"], linewidth=1.5, label=spec.label, **method_style(spec))
        plt.axhline(0.0, linewidth=0.9, color=REFERENCE_COLOR)
        plt.xlabel(xlabel)
        plt.ylabel("Range error: method magnitude - truth magnitude")
        plt.title(f"Truth-range error: {title_suffix}")
        style_axes(ax)
        plt.legend()
        savefig(out_dir / filename)


def plot_sigma_diagnostics(df: pd.DataFrame, specs: Sequence[PoseSpec], out_dir: Path) -> None:
    x, xlabel = elapsed_time_axis(df)
    for spec in specs:
        sigma = df[f"{spec.key}_range_3sigma"].to_numpy(dtype=float)
        err = df[f"{spec.key}_range_error"].to_numpy(dtype=float)
        if not np.any(np.isfinite(sigma)):
            continue

        plt.figure(figsize=(12, 5.5))
        ax = plt.gca()
        plt.plot(x, err, linewidth=1.5, label="range error", **method_style(spec))
        plt.plot(x, sigma, linewidth=1.1, color=REFERENCE_COLOR, linestyle="--", label="+3 sigma")
        plt.plot(x, -sigma, linewidth=1.1, color=REFERENCE_COLOR, linestyle="--", label="-3 sigma")
        plt.axhline(0.0, linewidth=0.9, color=REFERENCE_COLOR)
        plt.xlabel(xlabel)
        plt.ylabel("Range error")
        plt.title(f"Truth range error with approximate 3-sigma bound: {spec.label}")
        style_axes(ax)
        plt.legend()
        savefig(out_dir / f"truth_range_error_3sigma_{sanitize_name(spec.key)}.png")

        norm = df[f"{spec.key}_normalized_range_error"].to_numpy(dtype=float)
        if np.any(np.isfinite(norm)):
            plt.figure(figsize=(12, 5.5))
            ax = plt.gca()
            plt.plot(x, norm, linewidth=1.5, label="normalized range error", **method_style(spec))
            plt.axhline(3.0, linewidth=0.9, color=REFERENCE_COLOR, linestyle="--", label="+3")
            plt.axhline(-3.0, linewidth=0.9, color=REFERENCE_COLOR, linestyle="--", label="-3")
            plt.axhline(0.0, linewidth=0.9, color=REFERENCE_COLOR)
            plt.xlabel(xlabel)
            plt.ylabel("Range error / sigma")
            plt.title(f"Normalized truth-range error: {spec.label}")
            style_axes(ax)
            plt.legend()
            savefig(out_dir / f"truth_range_error_normalized_{sanitize_name(spec.key)}.png")


def plot_truth_scatter_and_histograms(df: pd.DataFrame, specs: Sequence[PoseSpec], out_dir: Path) -> None:
    truth = df["truth_range"].to_numpy(dtype=float)
    for family, suffix in [(None, "all_methods"), ("raw", "raw_methods"), ("fg", "fg_methods")]:
        subset = plot_specs_for_family(specs, family)
        if not subset:
            continue

        plt.figure(figsize=(7.5, 7))
        ax = plt.gca()
        finite_truth = truth[np.isfinite(truth)]
        if finite_truth.size:
            lo, hi = float(np.nanmin(finite_truth)), float(np.nanmax(finite_truth))
            plt.plot([lo, hi], [lo, hi], linewidth=1.0, color=REFERENCE_COLOR, linestyle="--", label="ideal")
        for spec in subset:
            y = df[f"{spec.key}_vision_range"].where(df[f"{spec.key}_truth_compare_valid"], np.nan).to_numpy(dtype=float)
            valid = np.isfinite(truth) & np.isfinite(y)
            if np.any(valid):
                style = method_style(spec)
                plt.scatter(
                    truth[valid], y[valid], s=14, alpha=0.72, label=spec.label,
                    color=style["color"], marker=method_marker(spec), edgecolors="none"
                )
        plt.xlabel("Truth vector magnitude")
        plt.ylabel("Method vector magnitude")
        plt.title(f"Range scatter against truth: {suffix.replace('_', ' ')}")
        style_axes(ax)
        plt.legend()
        savefig(out_dir / f"truth_range_scatter_{suffix}.png")

        plt.figure(figsize=(10, 5))
        ax = plt.gca()
        for spec in subset:
            err = df[f"{spec.key}_range_error"].to_numpy(dtype=float)
            err = err[np.isfinite(err)]
            if err.size:
                style = method_style(spec)
                plt.hist(err, bins=40, histtype="step", linewidth=1.4, label=spec.label, color=style["color"], linestyle=style["linestyle"])
        plt.axvline(0.0, linewidth=0.9, color=REFERENCE_COLOR)
        plt.xlabel("Range error")
        plt.ylabel("Count")
        plt.title(f"Truth-range error histogram: {suffix.replace('_', ' ')}")
        style_axes(ax)
        plt.legend()
        savefig(out_dir / f"truth_range_error_hist_{suffix}.png")


def plot_summary_bars(summary: pd.DataFrame, out_dir: Path) -> None:
    if summary.empty:
        return
    metrics = [
        ("range_error_rmse", "Range-error RMSE", "summary_truth_range_rmse.png"),
        ("abs_range_error_median", "Median absolute range error", "summary_truth_abs_range_median.png"),
        ("abs_range_error_p95", "95th percentile absolute range error", "summary_truth_abs_range_p95.png"),
        ("inside_3sigma_fraction", "Fraction inside approximate ±3 sigma", "summary_truth_inside_3sigma_fraction.png"),
    ]
    for metric, ylabel, filename in metrics:
        if metric not in summary.columns:
            continue
        vals = pd.to_numeric(summary[metric], errors="coerce")
        if not np.any(np.isfinite(vals)):
            continue
        plt.figure(figsize=(10, 5))
        ax = plt.gca()
        spec_by_key = {spec.key: spec for spec in POSE_SPECS}
        colors = [
            method_style(spec_by_key[key])["color"] if key in spec_by_key else "#4c4c4c"
            for key in summary.get("key", pd.Series([""] * len(summary)))
        ]
        plt.bar(summary["method"], vals, color=colors, edgecolor="none")
        plt.ylabel(ylabel)
        plt.title(ylabel)
        plt.xticks(rotation=25, ha="right")
        style_axes(ax)
        savefig(out_dir / filename)


def plot_raw_vs_own_fg(df: pd.DataFrame, pairs: Sequence[tuple[PoseSpec, PoseSpec]], out_dir: Path) -> None:
    x, xlabel = elapsed_time_axis(df)
    for raw, fg in pairs:
        pk = pair_key(raw, fg)
        base = sanitize_name(raw.base_key)

        plt.figure(figsize=(12, 6))
        ax = plt.gca()
        plt.plot(x, df["truth_range"], linewidth=2.2, color=TRUTH_COLOR, label="truth magnitude")
        plt.plot(x, df[f"{raw.key}_vision_range"].where(df[f"{raw.key}_truth_compare_valid"], np.nan), linewidth=1.5, label=raw.label, **method_style(raw))
        plt.plot(x, df[f"{fg.key}_vision_range"].where(df[f"{fg.key}_truth_compare_valid"], np.nan), linewidth=1.5, label=fg.label, **method_style(fg))
        plt.xlabel(xlabel)
        plt.ylabel("Range / vector magnitude")
        plt.title(f"Raw method vs its SE(3) factor graph: {raw.label}")
        style_axes(ax)
        plt.legend()
        savefig(out_dir / f"raw_vs_own_fg_range_tracking_{base}.png")

        plt.figure(figsize=(12, 5))
        ax = plt.gca()
        plt.plot(x, df[f"pair_{pk}_range_delta"], linewidth=1.5, label="raw range - FG range", **pair_style(raw, fg))
        plt.axhline(0.0, linewidth=0.9, color=REFERENCE_COLOR)
        plt.xlabel(xlabel)
        plt.ylabel("Range delta")
        plt.title(f"Raw minus own FG range delta: {raw.label}")
        style_axes(ax)
        plt.legend()
        savefig(out_dir / f"raw_vs_own_fg_range_delta_{base}.png")

        plt.figure(figsize=(12, 5))
        ax = plt.gca()
        plt.plot(x, df[f"pair_{pk}_vector_delta_norm"], linewidth=1.5, label="||raw vector - FG vector||", **pair_style(raw, fg))
        plt.xlabel(xlabel)
        plt.ylabel("Vector delta norm")
        plt.title(f"Raw vs own FG vector difference: {raw.label}")
        style_axes(ax)
        plt.legend()
        savefig(out_dir / f"raw_vs_own_fg_vector_delta_norm_{base}.png")

        plt.figure(figsize=(12, 5))
        ax = plt.gca()
        for axis in "xyz":
            axis_color = {"x": "#4c78a8", "y": "#59a14f", "z": "#e15759"}[axis]
            plt.plot(x, df[f"pair_{pk}_vec_delta_{axis}"], linewidth=1.3, label=f"{axis} delta", color=axis_color)
        plt.axhline(0.0, linewidth=0.9, color=REFERENCE_COLOR)
        plt.xlabel(xlabel)
        plt.ylabel("Vector component delta")
        plt.title(f"Raw vs own FG antenna-vector component deltas: {raw.label}")
        style_axes(ax)
        plt.legend()
        savefig(out_dir / f"raw_vs_own_fg_vector_component_delta_{base}.png")

        for suffix in ("probe", "tanker"):
            ppk = pose_pair_key(raw, fg, suffix)
            plt.figure(figsize=(12, 5))
            ax = plt.gca()
            plt.plot(x, df[f"posepair_{ppk}_translation_delta_norm"], linewidth=1.5, label="translation delta norm", **pair_style(raw, fg))
            plt.xlabel(xlabel)
            plt.ylabel("Pose translation delta norm")
            plt.title(f"{suffix.capitalize()} pose translation: raw vs own FG, {raw.label}")
            style_axes(ax)
            plt.legend()
            savefig(out_dir / f"raw_vs_own_fg_{suffix}_translation_delta_norm_{base}.png")

            plt.figure(figsize=(12, 5))
            ax = plt.gca()
            plt.plot(x, df[f"posepair_{ppk}_attitude_delta_deg"], linewidth=1.5, label="attitude delta", **pair_style(raw, fg))
            plt.xlabel(xlabel)
            plt.ylabel("Attitude delta (deg)")
            plt.title(f"{suffix.capitalize()} pose attitude: raw vs own FG, {raw.label}")
            style_axes(ax)
            plt.legend()
            savefig(out_dir / f"raw_vs_own_fg_{suffix}_attitude_delta_deg_{base}.png")


def plot_pairwise_group(
    df: pd.DataFrame,
    pairs: Sequence[tuple[PoseSpec, PoseSpec]],
    out_dir: Path,
    filename_prefix: str,
    title_prefix: str,
) -> None:
    if not pairs:
        return
    x, xlabel = elapsed_time_axis(df)

    plt.figure(figsize=(12, 6))
    ax = plt.gca()
    for a, b in pairs:
        pk = pair_key(a, b)
        plt.plot(x, df[f"pair_{pk}_range_delta"], linewidth=1.4, label=pair_label(a, b), **pair_style(a, b))
    plt.axhline(0.0, linewidth=0.9, color=REFERENCE_COLOR)
    plt.xlabel(xlabel)
    plt.ylabel("Range delta")
    plt.title(f"{title_prefix}: range deltas")
    style_axes(ax)
    plt.legend(fontsize="x-small")
    savefig(out_dir / f"{filename_prefix}_range_delta.png")

    plt.figure(figsize=(12, 6))
    ax = plt.gca()
    for a, b in pairs:
        pk = pair_key(a, b)
        plt.plot(x, df[f"pair_{pk}_vector_delta_norm"], linewidth=1.4, label=pair_label(a, b), **pair_style(a, b))
    plt.xlabel(xlabel)
    plt.ylabel("Vector delta norm")
    plt.title(f"{title_prefix}: antenna-vector delta norms")
    style_axes(ax)
    plt.legend(fontsize="x-small")
    savefig(out_dir / f"{filename_prefix}_vector_delta_norm.png")


def plot_pairwise_pose_group(
    df: pd.DataFrame,
    pairs: Sequence[tuple[PoseSpec, PoseSpec]],
    out_dir: Path,
    filename_prefix: str,
    title_prefix: str,
) -> None:
    if not pairs:
        return
    x, xlabel = elapsed_time_axis(df)
    for suffix in ("probe", "tanker"):
        plt.figure(figsize=(12, 6))
        ax = plt.gca()
        for a, b in pairs:
            pk = pose_pair_key(a, b, suffix)
            plt.plot(x, df[f"posepair_{pk}_translation_delta_norm"], linewidth=1.4, label=pair_label(a, b), **pair_style(a, b))
        plt.xlabel(xlabel)
        plt.ylabel("Pose translation delta norm")
        plt.title(f"{title_prefix}: {suffix} pose translation delta norms")
        style_axes(ax)
        plt.legend(fontsize="x-small")
        savefig(out_dir / f"{filename_prefix}_{suffix}_pose_translation_delta_norm.png")

        plt.figure(figsize=(12, 6))
        ax = plt.gca()
        for a, b in pairs:
            pk = pose_pair_key(a, b, suffix)
            plt.plot(x, df[f"posepair_{pk}_attitude_delta_deg"], linewidth=1.4, label=pair_label(a, b), **pair_style(a, b))
        plt.xlabel(xlabel)
        plt.ylabel("Attitude delta (deg)")
        plt.title(f"{title_prefix}: {suffix} pose attitude deltas")
        style_axes(ax)
        plt.legend(fontsize="x-small")
        savefig(out_dir / f"{filename_prefix}_{suffix}_pose_attitude_delta_deg.png")


def plot_smoothness(df: pd.DataFrame, specs: Sequence[PoseSpec], out_dir: Path) -> None:
    x, xlabel = elapsed_time_axis(df)
    for family, filename, title_suffix in [
        (None, "smoothness_range_rate_all_methods.png", "all methods"),
        ("raw", "smoothness_range_rate_raw_methods.png", "raw methods"),
        ("fg", "smoothness_range_rate_fg_methods.png", "SE(3) factor graphs"),
    ]:
        subset = plot_specs_for_family(specs, family)
        if not subset:
            continue
        plt.figure(figsize=(12, 6))
        ax = plt.gca()
        for spec in subset:
            y = df[f"{spec.key}_vision_range"].where(df[f"{spec.key}_truth_compare_valid"], np.nan).to_numpy(dtype=float)
            dy = np.full(len(df), np.nan, dtype=float)
            valid = np.isfinite(y) & np.isfinite(x)
            idx = np.where(valid)[0]
            if idx.size >= 2:
                dt = np.diff(x[idx])
                dr = np.diff(y[idx])
                good = np.isfinite(dt) & (dt > 0.0)
                rates = np.full_like(dr, np.nan, dtype=float)
                rates[good] = dr[good] / dt[good]
                dy[idx[1:]] = rates
            plt.plot(x, dy, linewidth=1.5, label=spec.label, **method_style(spec))
        plt.axhline(0.0, linewidth=0.9, color=REFERENCE_COLOR)
        plt.xlabel(xlabel)
        plt.ylabel("Range rate from synchronized samples")
        plt.title(f"Range-rate smoothness diagnostic: {title_suffix}")
        style_axes(ax)
        plt.legend()
        savefig(out_dir / filename)


def plot_native_fg_range_check(df: pd.DataFrame, specs: Sequence[PoseSpec], out_dir: Path) -> None:
    """Compare native per-object FG range column to ||tvec|| when available.

    This is a sanity plot for the FG columns themselves. It does not compare to
    truth and does not include lever-arm antenna reconstruction.
    """
    x, xlabel = elapsed_time_axis(df)
    for spec in specs:
        if spec.native_range_col is None:
            continue
        for suffix in ("probe", "tanker"):
            native_col = suffixed(spec.native_range_col, suffix)
            if native_col not in df.columns:
                continue
            _, _, pose_t_cols = spec_cols(spec, suffix)
            t = numeric(df, pose_t_cols)
            t_norm = vector_norm(t)
            native = numeric_series(df, native_col)
            diff = native - t_norm
            if not np.any(np.isfinite(diff)):
                continue
            plt.figure(figsize=(12, 5))
            ax = plt.gca()
            plt.plot(x, diff, linewidth=1.5, label="native FG range - ||tvec||", **method_style(spec))
            plt.axhline(0.0, linewidth=0.9, color=REFERENCE_COLOR)
            plt.xlabel(xlabel)
            plt.ylabel("Range consistency delta")
            plt.title(f"Native FG range consistency: {spec.label}, {suffix}")
            style_axes(ax)
            plt.legend()
            savefig(out_dir / f"native_fg_range_consistency_{sanitize_name(spec.key)}_{suffix}.png")


# -----------------------------------------------------------------------------
# Summary text
# -----------------------------------------------------------------------------

def build_summary_text(
    probe_csv: Path,
    tanker_csv: Path,
    novatel_txt: Path,
    df: pd.DataFrame,
    specs: Sequence[PoseSpec],
    sync_tolerance: float,
    truth_summary: pd.DataFrame,
    vector_summary: pd.DataFrame,
    pose_summary: pd.DataFrame,
    smoothness_summary: pd.DataFrame,
) -> str:
    lines: list[str] = []
    lines.append("Navcalcs + SE(3) factor-graph truth-range comparison")
    lines.append("======================================================")
    lines.append("")
    lines.append(f"Probe CSV:   {probe_csv.name}")
    lines.append(f"Tanker CSV:  {tanker_csv.name}")
    lines.append(f"TSPI file:   {novatel_txt.name}")
    lines.append(f"Rows after synchronization attempt: {len(df)}")
    lines.append(f"Synchronization tolerance: {sync_tolerance:.6g} s")
    finite_truth = df["truth_range_valid"].to_numpy(dtype=bool) if "truth_range_valid" in df.columns else np.zeros(len(df), dtype=bool)
    lines.append(f"Rows with matched truth magnitude: {int(np.sum(finite_truth))}")
    for label, col in [("Tanker", "tanker_time_error_s"), ("Truth", "truth_time_error_s")]:
        if col in df.columns:
            dt = df[col].to_numpy(dtype=float)
            dt = dt[np.isfinite(dt)]
            if dt.size:
                lines.append(f"{label} sync residual: median={np.median(dt):.6g} s, max_abs={np.max(np.abs(dt)):.6g} s")
    lines.append("")

    lines.append("Available pose/vector methods")
    lines.append("-----------------------------")
    for spec in specs:
        valid = df[f"{spec.key}_truth_compare_valid"].to_numpy(dtype=bool)
        truth_valid = valid & finite_truth
        sigma_valid = np.isfinite(df[f"{spec.key}_range_sigma"].to_numpy(dtype=float))
        lines.append(
            f"{spec.label}: vector samples={int(np.sum(valid))}, "
            f"truth-range samples={int(np.sum(truth_valid))}, "
            f"range-sigma samples={int(np.sum(sigma_valid))}"
        )
    lines.append("")

    lines.append("Best truth-range agreement")
    lines.append("--------------------------")
    usable = truth_summary[np.isfinite(pd.to_numeric(truth_summary["range_error_rmse"], errors="coerce"))].copy()
    if usable.empty:
        lines.append("No method had finite truth-range error statistics.")
    else:
        usable = usable.sort_values("range_error_rmse")
        for _, row in usable.head(5).iterrows():
            lines.append(
                f"{row['method']}: RMSE={row['range_error_rmse']:.6g}, "
                f"median abs={row['abs_range_error_median']:.6g}, "
                f"p95 abs={row['abs_range_error_p95']:.6g}, "
                f"samples={int(row['valid_samples'])}"
            )
    lines.append("")

    lines.append("Raw vs own FG highlights")
    lines.append("------------------------")
    own = vector_summary[vector_summary["comparison_class"] == "raw_vs_own_fg"].copy()
    if own.empty:
        lines.append("No raw/own-FG pairs were available.")
    else:
        for _, row in own.iterrows():
            lines.append(
                f"{row['pair']}: range-delta RMSE={row['range_delta_rmse']:.6g}, "
                f"median vector delta={row['vector_delta_norm_median']:.6g}, "
                f"p95 vector delta={row['vector_delta_norm_p95']:.6g}"
            )
    lines.append("")

    lines.append("FG-to-FG highlights")
    lines.append("-------------------")
    fg = vector_summary[vector_summary["comparison_class"] == "fg_vs_fg"].copy()
    if fg.empty:
        lines.append("No FG/FG pairs were available.")
    else:
        fg = fg.sort_values("vector_delta_norm_median")
        for _, row in fg.head(6).iterrows():
            lines.append(
                f"{row['pair']}: median vector delta={row['vector_delta_norm_median']:.6g}, "
                f"p95={row['vector_delta_norm_p95']:.6g}, "
                f"range-delta RMSE={row['range_delta_rmse']:.6g}"
            )
    lines.append("")

    lines.append("Smoothness highlights")
    lines.append("---------------------")
    smooth = smoothness_summary[np.isfinite(pd.to_numeric(smoothness_summary["vector_rate_norm_median"], errors="coerce"))].copy()
    if smooth.empty:
        lines.append("No finite smoothness statistics were available.")
    else:
        smooth = smooth.sort_values("vector_rate_norm_median")
        for _, row in smooth.head(5).iterrows():
            lines.append(
                f"{row['method']}: median vector-rate norm={row['vector_rate_norm_median']:.6g}, "
                f"p95 vector-rate norm={row['vector_rate_norm_p95']:.6g}, "
                f"median abs range-rate={row['abs_range_rate_median']:.6g}"
            )
    lines.append("")

    lines.append("Coordinate note")
    lines.append("---------------")
    lines.append(
        "Truth comparisons are range-only by design. The TSPI x/y/z vector components are "
        "stored in the merged table for auditing, but the default plots and statistics do "
        "not treat those components as directionally comparable to camera-frame pose outputs. "
        "Method-to-method comparisons do use x/y/z vector deltas because those vectors are "
        "computed inside the shared vision/navigation convention."
    )
    return "\n".join(lines)


# -----------------------------------------------------------------------------
# CLI / main
# -----------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Compare probe/tanker navcalcs pose estimates and SE(3) factor graphs against TSPI truth magnitude.")
    parser.add_argument("--probe-csv", type=Path, help="Probe/receiver navcalcs CSV.")
    parser.add_argument("--tanker-csv", type=Path, help="Tanker/target navcalcs CSV.")
    parser.add_argument("--novatel-txt", type=Path, help="Whitespace-delimited NovAtel/TSPI relative-vector text file.")
    parser.add_argument("--out", type=Path, default=None, help="Output directory. Defaults to truth_compare_<probe>_<tanker>_fg.")
    parser.add_argument("--sync-tolerance", type=float, default=0.075, help="Nearest-time synchronization tolerance in seconds. Default: 0.075.")
    parser.add_argument(
        "--truth-transform",
        type=float,
        nargs=9,
        default=None,
        metavar=("r11", "r12", "r13", "r21", "r22", "r23", "r31", "r32", "r33"),
        help="Optional row-major 3x3 transform applied to the TSPI vector before computing magnitude.",
    )
    parser.add_argument(
        "--truth-sign",
        default="1",
        choices=["1", "-1", "auto"],
        help="Accepted for backward compatibility. Sign does not affect range-only truth comparison.",
    )
    parser.add_argument(
        "--receiver-probe-to-antenna",
        type=float,
        nargs=3,
        default=DEFAULT_RECEIVER_PROBE_TO_ANTENNA.tolist(),
        metavar=("X", "Y", "Z"),
        help="Receiver probe-tip to receiver antenna lever arm in receiver/probe frame.",
    )
    parser.add_argument(
        "--tanker-center-to-antenna",
        type=float,
        nargs=3,
        default=DEFAULT_TANKER_CENTER_TO_ANTENNA.tolist(),
        metavar=("X", "Y", "Z"),
        help="Tanker geometric center to tanker antenna lever arm in tanker frame.",
    )
    parser.add_argument(
        "--plot-level",
        choices=["summary", "full", "exhaustive"],
        default="full",
        help=(
            "How many plots to write. summary gives the core truth/range plots; "
            "full adds FG/raw/pairwise diagnostics; exhaustive adds the extra pose/native-range goblin plots. Default: full."
        ),
    )
    parser.add_argument("--plot-dpi", type=int, default=160, help="PNG resolution. Default: 160.")
    parser.add_argument("--no-dialog", action="store_true", help="Disable file dialogs when required paths are omitted.")
    return parser.parse_args()


def maybe_dialog_paths(args: argparse.Namespace) -> argparse.Namespace:
    if args.no_dialog or (args.probe_csv and args.tanker_csv and args.novatel_txt):
        return args
    try:
        from tkinter import Tk, filedialog
        root = Tk()
        root.withdraw()
        if args.probe_csv is None:
            selected = filedialog.askopenfilename(title="Select probe/receiver navcalcs CSV", filetypes=[("CSV", "*.csv"), ("All files", "*.*")])
            args.probe_csv = Path(selected) if selected else None
        if args.tanker_csv is None:
            selected = filedialog.askopenfilename(title="Select tanker/target navcalcs CSV", filetypes=[("CSV", "*.csv"), ("All files", "*.*")])
            args.tanker_csv = Path(selected) if selected else None
        if args.novatel_txt is None:
            selected = filedialog.askopenfilename(title="Select NovAtel / TSPI text file", filetypes=[("Text", "*.txt *.dat *.csv"), ("All files", "*.*")])
            args.novatel_txt = Path(selected) if selected else None
        root.destroy()
    except Exception:
        return args
    return args


def main() -> None:
    global PLOT_DPI
    args = maybe_dialog_paths(parse_args())
    PLOT_DPI = int(args.plot_dpi)
    setup_matplotlib_style()
    if args.probe_csv is None or args.tanker_csv is None or args.novatel_txt is None:
        raise SystemExit("Provide --probe-csv, --tanker-csv, and --novatel-txt, or run without --no-dialog.")

    probe_csv = Path(args.probe_csv)
    tanker_csv = Path(args.tanker_csv)
    novatel_txt = Path(args.novatel_txt)
    out = args.out or Path(f"truth_compare_{probe_csv.stem}_{tanker_csv.stem}_fg")
    plots_dir = out / "plots"
    tables_dir = out / "tables"
    ensure_dir(out)
    ensure_dir(plots_dir)
    ensure_dir(tables_dir)

    receiver_probe_to_antenna = np.asarray(args.receiver_probe_to_antenna, dtype=float)
    tanker_center_to_antenna = np.asarray(args.tanker_center_to_antenna, dtype=float)
    truth_transform = np.asarray(args.truth_transform, dtype=float).reshape(3, 3) if args.truth_transform is not None else None

    probe = load_navcalcs(probe_csv)
    tanker = load_navcalcs(tanker_csv)
    tspi = load_novatel_tspi(novatel_txt)

    merged = merge_probe_tanker_truth(probe, tanker, tspi, sync_tolerance=float(args.sync_tolerance))

    specs = [spec for spec in POSE_SPECS if spec_available_for_vector(merged, spec)]
    if not specs:
        raise RuntimeError("No complete raw or factor-graph pose methods found after merging probe/tanker navcalcs files.")

    merged = compute_vision_vectors(merged, specs, receiver_probe_to_antenna, tanker_center_to_antenna)
    merged = add_truth_range(merged, truth_transform)
    merged = add_truth_range_errors(merged, specs)
    merged = add_pairwise_vector_differences(merged, specs)
    merged = add_pairwise_pose_differences(merged, specs)

    availability_summary = summarize_availability(merged, specs)
    truth_summary = summarize_truth_range_errors(merged, specs)
    vector_summary = summarize_pairwise_vectors(merged, specs)
    pose_summary = summarize_pairwise_poses(merged, specs)
    raw_fg_summary = summarize_raw_vs_own_fg(vector_summary, pose_summary)
    smoothness_summary = summarize_smoothness(merged, specs)

    merged.to_csv(tables_dir / "merged_truth_comparison.csv", index=False)
    availability_summary.to_csv(tables_dir / "method_availability_summary.csv", index=False)
    truth_summary.to_csv(tables_dir / "truth_range_error_summary.csv", index=False)
    vector_summary.to_csv(tables_dir / "pairwise_vector_summary.csv", index=False)
    pose_summary.to_csv(tables_dir / "pairwise_pose_summary.csv", index=False)
    raw_fg_summary.to_csv(tables_dir / "raw_vs_own_fg_summary.csv", index=False)
    smoothness_summary.to_csv(tables_dir / "smoothness_summary.csv", index=False)

    write_markdown_table(availability_summary, tables_dir / "method_availability_summary.md")
    write_markdown_table(truth_summary, tables_dir / "truth_range_error_summary.md")
    write_markdown_table(vector_summary, tables_dir / "pairwise_vector_summary.md")
    write_markdown_table(pose_summary, tables_dir / "pairwise_pose_summary.md")
    write_markdown_table(raw_fg_summary, tables_dir / "raw_vs_own_fg_summary.md")
    write_markdown_table(smoothness_summary, tables_dir / "smoothness_summary.md")

    raw_fg_pairs = raw_vs_own_fg_pairs(specs)
    fg_pairs = [(a, b) for a, b in itertools.combinations(specs, 2) if a.family == "fg" and b.family == "fg"]
    raw_pairs = [(a, b) for a, b in itertools.combinations(specs, 2) if a.family == "raw" and b.family == "raw"]
    raw_vs_other_fg_pairs = [
        (a, b) for a, b in itertools.combinations(specs, 2)
        if comparison_class(a, b) == "raw_vs_other_fg"
    ]

    # Plot levels:
    #   summary    -> core truth magnitude plots and summary bars
    #   full       -> plus FG/raw/pairwise/sigma diagnostics
    #   exhaustive -> plus object-pose pairwise and native FG consistency plots
    plot_truth_range_tracking(merged, specs, plots_dir)
    plot_truth_range_errors(merged, specs, plots_dir)
    plot_summary_bars(truth_summary, plots_dir)

    if args.plot_level in {"full", "exhaustive"}:
        plot_sigma_diagnostics(merged, specs, plots_dir)
        plot_truth_scatter_and_histograms(merged, specs, plots_dir)
        plot_raw_vs_own_fg(merged, raw_fg_pairs, plots_dir)
        plot_pairwise_group(merged, fg_pairs, plots_dir, "pairwise_fg_vs_fg", "FG vs FG")
        plot_pairwise_group(merged, raw_pairs, plots_dir, "pairwise_raw_vs_raw", "Raw method vs raw method")
        plot_smoothness(merged, specs, plots_dir)

    if args.plot_level == "exhaustive":
        plot_pairwise_group(merged, raw_vs_other_fg_pairs, plots_dir, "pairwise_raw_vs_other_fg", "Raw method vs other-method FG")
        plot_pairwise_pose_group(merged, fg_pairs, plots_dir, "pairwise_fg_vs_fg", "FG vs FG")
        plot_pairwise_pose_group(merged, raw_pairs, plots_dir, "pairwise_raw_vs_raw", "Raw method vs raw method")
        plot_native_fg_range_check(merged, specs, plots_dir)

    summary_text = build_summary_text(
        probe_csv=probe_csv,
        tanker_csv=tanker_csv,
        novatel_txt=novatel_txt,
        df=merged,
        specs=specs,
        sync_tolerance=float(args.sync_tolerance),
        truth_summary=truth_summary,
        vector_summary=vector_summary,
        pose_summary=pose_summary,
        smoothness_summary=smoothness_summary,
    )
    (out / "summary.txt").write_text(summary_text, encoding="utf-8")
    print(summary_text)
    if str(args.truth_sign) != "1":
        print("\nNote: --truth-sign was accepted for compatibility, but sign is irrelevant for range-only truth comparison.")
    print(f"\nWrote comparison outputs to: {out}")


if __name__ == "__main__":
    main()
