aprilTagSize: 0.168
calibFilepath: Calibrations/GenericAlvium864.txt
cam_index: 0
cam_to_log_time_offset: 0.0
crosshairs: false
cubemap: false
detectTags: true
detect_corners: false
detect_horizon: false
dp_ckptN: '200'
dp_conf_list: '0.80'
dp_gpu: true
dp_img_dir: ''
dp_prefetch: '32'
draw_chessboard: false
end_export_idx: 1
export_quality: Medium Quality
factor_graph: false
hideAprilTags: true
hud: false
hud_data_filepath: ''
hyper_focus: false
imageFilepath: C:/repos/jarvis_submodules/camera_calibration_python/Images/MOCAP
  Test/2025.Nov.12_16.02.58.6195201.UTC_CALIBTEST/2025.Nov.12_16.02.58.6195201.UTC_CALIBTEST/1.bmp
imageSource: Stream from Folder
lidarFilepath: C:/repos/jarvis_submodules/camera_calibration_python/LIDAR_Truth_Points.pkl
phase_correlation: false
playback_mode: fixed_fps
pnpLidarPoints: false
processingKernel: Unfiltered
qnpLidarPoints: false
rt_speed: 1.0
saveFolder: C:/repos/jarvis_submodules/camera_calibration_python/ProcessedImages/CalspanSubset/Conf0.4
secondsBetweenImages: 1.0
start_export_idx: 0
target_fps: 20.0
undistort: false
yoloBiasTracking: false
yoloFilepath: ''
yoloInference: false
yolo_conf: 0.75
yolo_iou: 1.0
